"""Generate the external tools' gravity-field inputs from the committed excerpt.

Phase 3 exit criterion 5 (D-15) requires GMAT and Orekit to propagate the
cross-tool missions with the *identical* (GM, R, coefficients) triple the
missions load from ``tests/golden/gravity/earth_egm2008_n20.srgrav``. This
script derives both external formats from the committed full-precision CSV
form of that field (the two committed forms are byte-locked to each other by
``tests/python/test_gravity_data.py``), truncated to the 8x8 slice the
missions use:

- ``tests/golden/crosstool/earth_egm2008_8x8.cof``  (GMAT harmonic-gravity
  potential file, fixed-width COF layout reverse-engineered column-for-column
  from the shipped ``data/gravity/earth/EGM96.cof`` of GMAT R2026a)
- ``tests/golden/crosstool/earth_egm2008_8x8.gfc``  (ICGEM format, read
  natively by Orekit's GravityFieldFactory)

Output bytes are a pure function of the committed CSV, so regeneration is
deterministic. Run from the repo root:

    python scripts/crosstool/gen_field_files.py

Format notes (documented deviations, quantified at generation time):

- The COF numeric fields are 21 characters wide (``%.14E``, 15 significant
  digits) because GMAT parses fixed columns; a binary64 needs up to 17
  significant digits to round-trip, so each COF coefficient can differ from
  the committed binary64 by at most 1 part in 1e15. The worst relative
  deviation over the 8x8 slice is printed and recorded in the manifest; the
  acceleration impact is below 1e-18 relative (harmonic terms are at most
  1e-3 of the central term).
- The GFC values are written with ``repr()`` (shortest round-trip form), so
  Java's ``Double.parseDouble`` recovers the committed binary64 exactly.
- GM and R print exactly (both are short decimals), so the central term is
  bit-identical across all three tools.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "python"))

from star_reacher.data_fetch import read_coeffs_csv  # noqa: E402

CSV_PATH = REPO_ROOT / "tests" / "golden" / "gravity" / "earth_egm2008_n20.csv"
OUT_DIR = REPO_ROOT / "tests" / "golden" / "crosstool"
DEGREE = 8


def cof_text(field) -> str:
    """GMAT COF form. Layout matches the shipped EGM96.cof byte-for-byte:

    ``POTFIELD`` + degree(%3d) + order(%3d) + ``  1`` + GM, R, scale as
    ``%21.14E``; ``RECOEF`` + n(%5d) + m(%3d) + C(%24.14E) [+ S(%21.14E)];
    zonal rows omit the S field and degrees 0..1 are omitted entirely,
    exactly as in the shipped file (C00 = 1 is implied by GMAT, and this
    field's degree-1 coefficients are exactly zero).
    """
    lines = [
        "COMMENT   5",
        "CCCCC  ------------------------------------------------------------------  CCCCC",
        "CCCCC  earth_egm2008_8x8.cof : EGM2008 truncated to 8x8, generated from     CCCCC",
        "CCCCC  tests/golden/gravity/earth_egm2008_n20.csv by                        CCCCC",
        "CCCCC  scripts/crosstool/gen_field_files.py (star_reacher, D-15).           CCCCC",
        "CCCCC  ------------------------------------------------------------------  CCCCC",
        "POTFIELD%3d%3d  1%21.14E%21.14E%21.14E"
        % (DEGREE, DEGREE, field.gm_m3ps2, field.ref_radius_m, 1.0),
    ]
    for n in range(2, DEGREE + 1):
        for m in range(0, n + 1):
            row = "RECOEF%5d%3d%24.14E" % (n, m, field.cbar[n, m])
            if m > 0:
                row += "%21.14E" % field.sbar[n, m]
            lines.append(row)
    lines.append("END ")
    return "\n".join(lines) + "\n"


def gfc_text(field) -> str:
    """ICGEM form for Orekit; values in repr() so parsing is bit-exact."""
    lines = [
        "begin_of_head =========================================================",
        "generated by scripts/crosstool/gen_field_files.py (star_reacher, D-15)",
        "from the committed excerpt tests/golden/gravity/earth_egm2008_n20.csv,",
        "truncated to 8x8; identical GM/R/coefficients to the field the",
        "cross-tool missions load. Source model: EGM2008 (Pavlis et al. 2012).",
        "",
        "product_type                gravity_field",
        "modelname                   EGM2008_8x8_star_reacher",
        "earth_gravity_constant      %r" % field.gm_m3ps2,
        "radius                      %r" % field.ref_radius_m,
        "max_degree                  %d" % DEGREE,
        "errors                      no",
        "norm                        fully_normalized",
        "tide_system                 tide_free",
        "end_of_head ===========================================================",
    ]
    for n in range(0, DEGREE + 1):
        for m in range(0, n + 1):
            # float() strips the numpy scalar type so repr() is the plain
            # shortest round-trip decimal, not "np.float64(...)".
            lines.append(
                "gfc %3d %3d  %-24r %-24r"
                % (n, m, float(field.cbar[n, m]), float(field.sbar[n, m]))
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    field = read_coeffs_csv(CSV_PATH).truncated(DEGREE, DEGREE)

    # Quantify the COF 15-significant-digit rounding against the committed
    # binary64 values (the GFC round-trips exactly by construction).
    worst = 0.0
    for n in range(2, DEGREE + 1):
        for m in range(0, n + 1):
            for v in (field.cbar[n, m], field.sbar[n, m]):
                if v != 0.0:
                    rt = float("%.14E" % v)
                    worst = max(worst, abs(rt - v) / abs(v))

    outputs = {
        OUT_DIR / "earth_egm2008_8x8.cof": cof_text(field),
        OUT_DIR / "earth_egm2008_8x8.gfc": gfc_text(field),
    }
    for path, text in outputs.items():
        path.write_text(text, newline="\n", encoding="ascii")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        print(f"{path.name}: {len(text)} bytes, sha256 {digest}")
    print(f"COF 15-digit rounding: worst relative deviation {worst:.3e}")
    print(f"source CSV: {CSV_PATH.name}, GM {field.gm_m3ps2!r}, R {field.ref_radius_m!r}")


if __name__ == "__main__":
    main()
