"""``star data fetch`` implementation: dataset download and repack (D-8, FR-4, FR-5).

One-time maintainer-side pipelines, one per dataset:

- ``de440s``: download the JPL DE440s planetary SPK and the DE440 lunar
  principal-axis binary PCK, verify both against pinned SHA-256 values, and
  repack the segments star_reacher needs (Sun, EMB, Earth, Moon, Venus
  barycenter, Mars barycenter, Jupiter barycenter, lunar libration angles;
  2020-01-01 through 2060-01-01 TDB) into one small SREPH v1 binary file that
  the C++ core loads directly. The Chebyshev coefficients are copied verbatim
  from the source kernels - never refitted - so the repack inherits DE440
  accuracy exactly (format specification: ``docs/formats/sreph_v1.md``).
- ``egm2008`` / ``grgm1200a`` / ``mro120f`` (FR-5): download the published
  spherical-harmonic gravity coefficient file for Earth, Moon, or Mars,
  verify it against a pinned SHA-256, and repack the fully normalized
  C-bar/S-bar coefficients (truncated to the FR-5 degree: 70x70, 120x120,
  80x80 respectively) together with the source file's own GM and reference
  radius into one small SRGRAV v1 binary file for the C++ core (format
  specification: ``docs/formats/srgrav_v1.md``).

The module also carries pure-Python SREPH/SRGRAV readers; the SREPH reader
doubles as the executable specification of the C++ Chebyshev evaluator
(``cpp/src/ephemeris.cpp``): both implement the identical operation sequence,
so on IEEE-754 double hardware with FMA contraction disabled (D-10 build
flags) they produce bit-identical outputs. The committed bit-level golden
vectors under ``tests/golden/ephemeris/`` are generated by this evaluator.

Everything here runs before t0 (D-2 boundary rule): network, text, and
checksum handling stay in Python; the core only ever sees the binary SREPH
and SRGRAV files.
"""

from __future__ import annotations

import hashlib
import json
import math
import struct
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Source kernels and their pinned checksums
# ---------------------------------------------------------------------------

# JPL Solar System Dynamics distribution point for the DE440s planetary
# ephemeris SPK (Park, Folkner, Williams, and Boggs, "The JPL Planetary and
# Lunar Ephemerides DE440 and DE441", AJ 161:105, 2021). DE440s is the
# short-span (1849-2150) excerpt of DE440 published by JPL alongside it.
DE440S_URL = "https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de440s.bsp"
DE440S_SIZE_BYTES = 32726016
# SHA-256 of de440s.bsp as downloaded from DE440S_URL on 2026-07-02. JPL does
# not publish a checksum for this file, so the pin records the exact bytes
# this project validated: the repack of THIS file matches JPL Horizons
# geometric states to well under 1 m at 21 epochs spanning 2020-2060 (see
# tests/golden/ephemeris/manifest.toml and full_span_validation.md). A future
# download that fails this pin is a different file and must be re-validated,
# not silently accepted.
DE440S_SHA256 = "c1c7feeab882263fc493a9d5a5b2ddd71b54826cdf65d8d17a76126b260a49f2"

# NAIF generic-kernels distribution point for the DE440 lunar principal-axis
# orientation binary PCK (Euler angles of the Moon PA frame, i.e. the lunar
# librations integrated with DE440; same Park et al. 2021 reference).
MOON_PA_URL = (
    "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/moon_pa_de440_200625.bpc"
)
MOON_PA_SIZE_BYTES = 12863488
# SHA-256 of moon_pa_de440_200625.bpc as downloaded from MOON_PA_URL on
# 2026-07-02; same pin policy as DE440S_SHA256 (validated content, recorded
# bytes). Libration output from the repack of THIS file matches jplephem's
# independent evaluation of the same kernel (tests/golden/ephemeris/).
MOON_PA_SHA256 = "60cd55aa401ea2ea97360636f567554bfe4e37bb829f901b4460a455dfaf783f"

# ---------------------------------------------------------------------------
# Repack span (D-8: 2020-2060) in TDB seconds since J2000 TDB
# ---------------------------------------------------------------------------

# J2000 is JD 2451545.0 TDB (2000-01-01T12:00:00 TDB). Both bounds fall on
# TDB midnights, which are exactly representable in binary64 both as Julian
# dates (half-integers) and as seconds since J2000 (multiples of 43200), so
# no quantization enters the span arithmetic.
SPAN_START_TDB_S = 631108800.0  # 2020-01-01T00:00:00 TDB = JD 2458849.5
SPAN_END_TDB_S = 1893412800.0  # 2060-01-01T00:00:00 TDB = JD 2473459.5

# Segment kinds in the SREPH file (docs/formats/sreph_v1.md section 4).
KIND_POSITION_KM = 0  # SPK Type 2: position Chebyshev coefficients [km]
KIND_ANGLES_RAD = 1  # PCK Type 2: Euler-angle Chebyshev coefficients [rad]

# Bodies repacked from de440s.bsp: (name, NAIF target, NAIF center).
# Moon and Earth are carried relative to the Earth-Moon barycenter exactly as
# DE440 stores them; the geocentric Moon state is composed at evaluation time
# as moon - earth (both EMB-relative), never re-fitted.
SPK_BODIES = (
    ("sun", 10, 0),
    ("emb", 3, 0),
    ("earth", 399, 3),
    ("moon", 301, 3),
    ("venus_bary", 2, 0),
    ("mars_bary", 4, 0),
    ("jupiter_bary", 5, 0),
)
# Lunar librations from the binary PCK: body 31008 is the NAIF class ID of
# the MOON_PA_DE440 frame; its "center" slot carries the PCK reference frame
# (1 = J2000). The three components are the 3-1-3 Euler angles phi, theta,
# psi of the lunar principal-axis frame relative to the ICRF equator.
LIBRATION_NAME = "moon_librations"
LIBRATION_BODY = 31008
LIBRATION_FRAME = 1

SREPH_MAGIC = b"SREPH\x00\r\n"  # NUL + CRLF tripwire, mirroring SRLOG (D-11)
SREPH_VERSION_MAJOR = 1
SREPH_VERSION_MINOR = 0
_HEADER_SIZE = 96
_DIR_ENTRY_SIZE = 64

REPACK_FILENAME = "de440s_2020_2060.sreph"
MANIFEST_FILENAME = "de440s_manifest.json"


class DataFetchError(Exception):
    """A fetch, checksum, or repack step failed; the message says which."""


# ---------------------------------------------------------------------------
# SREPH v1 container
# ---------------------------------------------------------------------------


@dataclass
class SrephSegment:
    """One repacked Chebyshev segment (docs/formats/sreph_v1.md section 4)."""

    name: str
    target: int
    center: int
    kind: int
    init_tdb_s: float
    intlen_s: float
    coeffs: np.ndarray  # (n_records, 3, n_coeffs) float64, verbatim from DAF

    @property
    def n_records(self) -> int:
        return int(self.coeffs.shape[0])

    @property
    def n_coeffs(self) -> int:
        return int(self.coeffs.shape[2])

    @property
    def end_tdb_s(self) -> float:
        return self.init_tdb_s + self.n_records * self.intlen_s


def write_sreph(
    path: Path,
    segments: list[SrephSegment],
    source_spk_sha256: str,
    source_pck_sha256: str,
) -> None:
    """Write an SREPH v1 file. Output bytes are a pure function of the inputs."""
    dir_bytes = bytearray()
    data_bytes = bytearray()
    data_offset = _HEADER_SIZE + _DIR_ENTRY_SIZE * len(segments)
    for seg in segments:
        name_bytes = seg.name.encode("ascii")
        if len(name_bytes) > 15:
            raise DataFetchError(f"segment name too long for SREPH v1: {seg.name!r}")
        if seg.coeffs.shape[1] != 3 or seg.coeffs.dtype != np.float64:
            raise DataFetchError(f"segment {seg.name!r}: coefficients must be (n,3,m) float64")
        dir_bytes += struct.pack(
            "<16sIIIIddIIQ",
            name_bytes,
            seg.target,
            seg.center,
            seg.kind,
            seg.n_coeffs,
            seg.init_tdb_s,
            seg.intlen_s,
            seg.n_records,
            0,  # reserved
            data_offset + len(data_bytes),
        )
        # '<' packing plus float64 tobytes keeps the file little-endian on
        # every host, per the format's fixed-endianness rule.
        data_bytes += np.ascontiguousarray(seg.coeffs, dtype="<f8").tobytes()
    span_start = max(seg.init_tdb_s for seg in segments)
    span_end = min(seg.end_tdb_s for seg in segments)
    header = struct.pack(
        "<8sHHIdd32s32s",
        SREPH_MAGIC,
        SREPH_VERSION_MAJOR,
        SREPH_VERSION_MINOR,
        len(segments),
        span_start,
        span_end,
        bytes.fromhex(source_spk_sha256),
        bytes.fromhex(source_pck_sha256),
    )
    assert len(header) == _HEADER_SIZE
    path.write_bytes(header + bytes(dir_bytes) + bytes(data_bytes))


@dataclass
class SrephFile:
    """Parsed SREPH v1 file (reference reader mirroring the C++ loader)."""

    span_start_tdb_s: float
    span_end_tdb_s: float
    source_spk_sha256: str
    source_pck_sha256: str
    segments: list[SrephSegment]

    def segments_named(self, name: str) -> list[SrephSegment]:
        found = [s for s in self.segments if s.name == name]
        if not found:
            names = sorted({s.name for s in self.segments})
            raise KeyError(f"sreph: unknown body {name!r}; available: {names}")
        return found

    def segment_for(self, name: str, tdb_s: float) -> SrephSegment:
        candidates = self.segments_named(name)
        for seg in candidates:
            if seg.init_tdb_s <= tdb_s <= seg.end_tdb_s:
                return seg
        raise ValueError(
            f"sreph: epoch {tdb_s!r} s TDB is outside every stored segment of "
            f"{name!r}; refusing to extrapolate"
        )


def read_sreph(path: Path) -> SrephFile:
    data = Path(path).read_bytes()
    if len(data) < _HEADER_SIZE or data[:8] != SREPH_MAGIC:
        raise DataFetchError(f"{path}: not an SREPH file (bad magic or truncated header)")
    (major, minor, seg_count, span_start, span_end, spk_sha, pck_sha) = struct.unpack(
        "<HHIdd32s32s", data[8:_HEADER_SIZE]
    )
    if major != SREPH_VERSION_MAJOR:
        raise DataFetchError(
            f"{path}: SREPH major version {major} is not supported (reader implements "
            f"{SREPH_VERSION_MAJOR})"
        )
    del minor  # additive minor versions change nothing this reader consumes
    segments: list[SrephSegment] = []
    for i in range(seg_count):
        entry_off = _HEADER_SIZE + i * _DIR_ENTRY_SIZE
        entry = data[entry_off : entry_off + _DIR_ENTRY_SIZE]
        if len(entry) != _DIR_ENTRY_SIZE:
            raise DataFetchError(f"{path}: truncated segment directory")
        (name_raw, target, center, kind, n_coeffs, init, intlen, n_records, _res, off) = (
            struct.unpack("<16sIIIIddIIQ", entry)
        )
        nbytes = n_records * 3 * n_coeffs * 8
        if off + nbytes > len(data):
            raise DataFetchError(f"{path}: segment {i} coefficient block runs past EOF")
        coeffs = np.frombuffer(data, dtype="<f8", count=n_records * 3 * n_coeffs, offset=off)
        segments.append(
            SrephSegment(
                name=name_raw.rstrip(b"\x00").decode("ascii"),
                target=target,
                center=center,
                kind=kind,
                init_tdb_s=init,
                intlen_s=intlen,
                coeffs=coeffs.reshape(n_records, 3, n_coeffs),
            )
        )
    return SrephFile(
        span_start_tdb_s=span_start,
        span_end_tdb_s=span_end,
        source_spk_sha256=spk_sha.hex(),
        source_pck_sha256=pck_sha.hex(),
        segments=segments,
    )


# ---------------------------------------------------------------------------
# Reference Chebyshev evaluator (the executable spec of cpp/src/ephemeris.cpp)
# ---------------------------------------------------------------------------


def evaluate_segment(seg: SrephSegment, tdb_s: float) -> tuple[list[float], list[float]]:
    """Evaluate one segment at ``tdb_s``; returns (values, rates) in native units.

    Kind 0 segments yield km and km/s; kind 1 yields rad and rad/s. The
    operation sequence below is mirrored statement-for-statement by
    ``star::Ephemeris`` in ``cpp/src/ephemeris.cpp`` (labels
    eq:ephemeris:timescale, eq:ephemeris:recurrence, eq:ephemeris:series in
    the math library chapter); any change here is a change to the bit-level
    golden contract and must be made in both places.
    """
    if not (seg.init_tdb_s <= tdb_s <= seg.end_tdb_s):
        raise ValueError(f"epoch {tdb_s!r} outside segment [{seg.init_tdb_s}, {seg.end_tdb_s}]")
    # Record selection: the boundary epoch between records k-1 and k belongs
    # to record k; the segment's final epoch (which would select record n)
    # clamps to the last record and evaluates at x = +1 exactly.
    k = math.floor((tdb_s - seg.init_tdb_s) / seg.intlen_s)
    n = seg.n_records
    if k >= n:
        k = n - 1
    if k < 0:
        k = 0
    # eq:ephemeris:timescale
    t0 = seg.init_tdb_s + k * seg.intlen_s
    x = 2.0 * (tdb_s - t0) / seg.intlen_s - 1.0
    ncoef = seg.n_coeffs
    T = [0.0] * ncoef
    dT = [0.0] * ncoef
    T[0] = 1.0
    if ncoef > 1:
        T[1] = x
        dT[1] = 1.0
    # eq:ephemeris:recurrence
    for j in range(2, ncoef):
        T[j] = 2.0 * x * T[j - 1] - T[j - 2]
        dT[j] = 2.0 * T[j - 1] + 2.0 * x * dT[j - 1] - dT[j - 2]
    values: list[float] = []
    rates: list[float] = []
    rec = seg.coeffs[k]
    # eq:ephemeris:series - fixed ascending accumulation order (D-10)
    for comp in range(3):
        acc = 0.0
        acc_d = 0.0
        for j in range(ncoef):
            c = float(rec[comp][j])
            acc = acc + c * T[j]
            acc_d = acc_d + c * dT[j]
        values.append(acc)
        rates.append(acc_d * (2.0 / seg.intlen_s))
    return values, rates


def evaluate_state_m(
    sreph: SrephFile, name: str, tdb_s: float
) -> tuple[list[float], list[float]]:
    """Position [m] and velocity [m/s] of ``name`` relative to its center."""
    seg = sreph.segment_for(name, tdb_s)
    if seg.kind != KIND_POSITION_KM:
        raise ValueError(f"{name!r} is not a position segment")
    v, r = evaluate_segment(seg, tdb_s)
    return [c * 1000.0 for c in v], [c * 1000.0 for c in r]


def evaluate_librations(sreph: SrephFile, tdb_s: float) -> tuple[list[float], list[float]]:
    """Lunar libration Euler angles [rad] and rates [rad/s]."""
    seg = sreph.segment_for(LIBRATION_NAME, tdb_s)
    if seg.kind != KIND_ANGLES_RAD:
        raise ValueError(f"{LIBRATION_NAME!r} is not an angle segment")
    return evaluate_segment(seg, tdb_s)


# ---------------------------------------------------------------------------
# DAF Type 2 extraction (verbatim coefficients)
# ---------------------------------------------------------------------------


def _extract_type2(daf, start_i: int, end_i: int) -> tuple[float, float, np.ndarray]:
    """Return (init, intlen, coeffs (n,3,m)) copied verbatim from a DAF array.

    SPK Type 2 and binary-PCK Type 2 share this layout (SPK Required Reading,
    NAIF): N records of RSIZE doubles - MID, RADIUS, then the Chebyshev
    coefficients of the three components in ascending order - followed by a
    four-double trailer INIT, INTLEN, RSIZE, N. MID and RADIUS are dropped:
    they are exactly INIT + (k + 1/2) * INTLEN and INTLEN / 2 for every DE
    Type 2 segment, so the retained INIT/INTLEN reproduce them.
    """
    trailer = np.array(daf.read_array(end_i - 3, end_i), dtype=np.float64)
    init, intlen, rsize, n = (float(trailer[0]), float(trailer[1]), int(trailer[2]), int(trailer[3]))
    ncoef = (rsize - 2) // 3
    if rsize != 2 + 3 * ncoef:
        raise DataFetchError(f"unsupported Type 2 record size {rsize}")
    raw = np.array(daf.read_array(start_i, end_i - 4), dtype=np.float64)
    if raw.size != n * rsize:
        raise DataFetchError(f"Type 2 payload size {raw.size} != N*RSIZE = {n * rsize}")
    records = raw.reshape(n, rsize)
    # Sanity-pin the redundant bookkeeping we drop, so a kernel that violated
    # the constant-interval assumption could never repack silently wrong.
    if not (
        records[0, 0] == init + 0.5 * intlen and records[0, 1] == 0.5 * intlen
    ):
        raise DataFetchError("Type 2 MID/RADIUS do not match INIT/INTLEN")
    return init, intlen, records[:, 2:].reshape(n, 3, ncoef).copy()


def _trim_records(
    init: float, intlen: float, coeffs: np.ndarray, t_lo: float, t_hi: float
) -> tuple[float, np.ndarray]:
    """Keep the whole records covering [t_lo, t_hi]; never split a record."""
    n = coeffs.shape[0]
    k_lo = int(math.floor((t_lo - init) / intlen))
    k_hi = int(math.floor((t_hi - init) / intlen))
    if k_hi * intlen + init == t_hi:
        k_hi -= 1  # t_hi on a boundary: the record ending there covers it
    if k_lo < 0 or k_hi >= n:
        raise DataFetchError(
            f"requested span [{t_lo}, {t_hi}] s TDB exceeds source segment coverage"
        )
    return init + k_lo * intlen, coeffs[k_lo : k_hi + 1].copy()


def repack(spk_path: Path, pck_path: Path, out_path: Path) -> SrephFile:
    """Repack the D-8 body set from the source kernels into ``out_path``."""
    # Imported here, not module-level: jplephem is a runtime dependency, but
    # only this maintainer-side path needs it (D-12 data-prep role).
    from jplephem.pck import PCK
    from jplephem.spk import SPK

    segments: list[SrephSegment] = []
    spk = SPK.open(str(spk_path))
    try:
        by_key = {(s.target, s.center): s for s in spk.segments}
        for name, target, center in SPK_BODIES:
            src = by_key.get((target, center))
            if src is None:
                raise DataFetchError(
                    f"{spk_path}: no segment for target {target} center {center} ({name})"
                )
            if src.data_type != 2:
                raise DataFetchError(f"{spk_path}: segment {name} is not SPK Type 2")
            init, intlen, coeffs = _extract_type2(spk.daf, src.start_i, src.end_i)
            init_trim, coeffs_trim = _trim_records(
                init, intlen, coeffs, SPAN_START_TDB_S, SPAN_END_TDB_S
            )
            segments.append(
                SrephSegment(name, target, center, KIND_POSITION_KM, init_trim, intlen, coeffs_trim)
            )
    finally:
        spk.close()

    pck = PCK.open(str(pck_path))
    try:
        lib_segments = [s for s in pck.segments if s.body == LIBRATION_BODY and s.data_type == 2]
        covering = [
            s
            for s in lib_segments
            if s.initial_second <= SPAN_START_TDB_S and s.final_second >= SPAN_END_TDB_S
        ]
        if not covering:
            raise DataFetchError(
                f"{pck_path}: no Type 2 segment for body {LIBRATION_BODY} covers the repack span"
            )
        src = covering[0]
        init, intlen, coeffs = _extract_type2(pck.daf, src.start_i, src.end_i)
        init_trim, coeffs_trim = _trim_records(
            init, intlen, coeffs, SPAN_START_TDB_S, SPAN_END_TDB_S
        )
        segments.append(
            SrephSegment(
                LIBRATION_NAME,
                LIBRATION_BODY,
                LIBRATION_FRAME,
                KIND_ANGLES_RAD,
                init_trim,
                intlen,
                coeffs_trim,
            )
        )
    finally:
        pck.daf.file.close()

    write_sreph(out_path, segments, _sha256(spk_path), _sha256(pck_path))
    return read_sreph(out_path)


# ---------------------------------------------------------------------------
# Fetch orchestration
# ---------------------------------------------------------------------------


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _download(url: str, dest: Path) -> None:
    print(f"downloading {url} -> {dest} ...", flush=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    with urllib.request.urlopen(url) as resp, open(tmp, "wb") as out:
        while True:
            chunk = resp.read(1 << 20)
            if not chunk:
                break
            out.write(chunk)
    tmp.replace(dest)


def _ensure_source(url: str, expected_sha256: str, dest: Path) -> str:
    """Download ``dest`` unless a checksum-verified copy is already present."""
    if dest.is_file():
        got = _sha256(dest)
        if got == expected_sha256:
            print(f"{dest.name}: present, SHA-256 verified ({got[:12]}...)")
            return got
        raise DataFetchError(
            f"{dest}: SHA-256 mismatch.\n  expected {expected_sha256}\n  got      {got}\n"
            f"The file on disk is not the validated kernel. Delete it to re-download, "
            f"or update the pinned hash only after re-running the Horizons validation "
            f"(tests/golden/ephemeris/generate.py)."
        )
    _download(url, dest)
    got = _sha256(dest)
    if got != expected_sha256:
        raise DataFetchError(
            f"{dest}: downloaded file fails the SHA-256 pin.\n"
            f"  expected {expected_sha256}\n  got      {got}\n"
            f"JPL may have republished the kernel; do not use it until it is "
            f"re-validated against Horizons and the pin is updated."
        )
    print(f"{dest.name}: downloaded, SHA-256 verified ({got[:12]}...)")
    return got


def fetch_de440s(data_dir: Path) -> Path:
    """Fetch and repack DE440s; idempotent. Returns the repack path."""
    data_dir = Path(data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    spk_path = data_dir / "de440s.bsp"
    pck_path = data_dir / "moon_pa_de440_200625.bpc"
    out_path = data_dir / REPACK_FILENAME
    manifest_path = data_dir / MANIFEST_FILENAME

    spk_sha = _ensure_source(DE440S_URL, DE440S_SHA256, spk_path)
    pck_sha = _ensure_source(MOON_PA_URL, MOON_PA_SHA256, pck_path)

    if out_path.is_file() and manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            manifest = {}
        recorded = manifest.get("repack_sha256")
        if recorded and _sha256(out_path) == recorded:
            print(f"{out_path.name}: present, SHA-256 verified ({recorded[:12]}...)")
            print(f"data fetch de440s: verified, nothing to do ({out_path})")
            return out_path

    sreph = repack(spk_path, pck_path, out_path)
    repack_sha = _sha256(out_path)
    manifest_path.write_text(
        json.dumps(
            {
                "dataset": "de440s",
                "format": "SREPH",
                "format_version": f"{SREPH_VERSION_MAJOR}.{SREPH_VERSION_MINOR}",
                "sources": [
                    {"url": DE440S_URL, "sha256": spk_sha},
                    {"url": MOON_PA_URL, "sha256": pck_sha},
                ],
                "repack_file": out_path.name,
                "repack_sha256": repack_sha,
                "span_tdb_s": [sreph.span_start_tdb_s, sreph.span_end_tdb_s],
                "segments": [
                    {
                        "name": s.name,
                        "target": s.target,
                        "center": s.center,
                        "kind": s.kind,
                        "records": s.n_records,
                        "coefficients": s.n_coeffs,
                        "interval_s": s.intlen_s,
                    }
                    for s in sreph.segments
                ],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    size_kib = out_path.stat().st_size / 1024.0
    print(
        f"repacked {len(sreph.segments)} segments, span "
        f"[{sreph.span_start_tdb_s:.0f}, {sreph.span_end_tdb_s:.0f}] s TDB, "
        f"{size_kib:.0f} KiB -> {out_path}"
    )
    print(f"data fetch de440s: complete ({out_path})")
    return out_path


# ---------------------------------------------------------------------------
# SRGRAV v1 container (FR-5 gravity coefficient sets; docs/formats/srgrav_v1.md)
# ---------------------------------------------------------------------------

SRGRAV_MAGIC = b"SRGRV\x00\r\n"  # NUL + CRLF tripwire, mirroring SREPH/SRLOG
SRGRAV_VERSION_MAJOR = 1
SRGRAV_VERSION_MINOR = 0
_SRGRAV_HEADER_SIZE = 96
_SRGRAV_HEADER_FMT = "<8sHHIIIIdd16s32sI"

# Tide-system codes (srgrav_v1.md section 4). The tide system never enters
# evaluation; it documents the permanent-tide convention of the stored C(2,0)
# so cross-tool comparisons use consistent coefficients.
TIDE_SYSTEM_CODES = {"tide_free": 0, "zero_tide": 1, "mean_tide": 2, "unknown": 3}
TIDE_SYSTEM_NAMES = {v: k for k, v in TIDE_SYSTEM_CODES.items()}


@dataclass
class GravityCoefficients:
    """One spherical-harmonic gravity field: header metadata + C-bar/S-bar.

    ``cbar``/``sbar`` are (n_max+1, n_max+1) float64 arrays indexed [n, m],
    fully normalized (4-pi geodesy normalization), zero above the diagonal
    and above ``m_max``. GM and the reference radius come from the source
    file's own header: each field is a self-consistent (GM, R, coefficients)
    triple and must never be mixed with another source's constants.
    """

    name: str
    gm_m3ps2: float
    ref_radius_m: float
    n_max: int
    m_max: int
    tide_system: str  # key of TIDE_SYSTEM_CODES
    cbar: np.ndarray
    sbar: np.ndarray
    source_sha256: str

    def truncated(self, n_max: int, m_max: int | None = None) -> "GravityCoefficients":
        """A copy truncated to degree ``n_max`` (and order ``m_max``)."""
        if m_max is None:
            m_max = n_max
        if n_max > self.n_max or m_max > self.m_max:
            raise DataFetchError(
                f"cannot truncate {self.name} to {n_max}x{m_max}: source holds "
                f"only {self.n_max}x{self.m_max}"
            )
        cbar = self.cbar[: n_max + 1, : n_max + 1].copy()
        sbar = self.sbar[: n_max + 1, : n_max + 1].copy()
        if m_max < n_max:
            cbar[:, m_max + 1 :] = 0.0
            sbar[:, m_max + 1 :] = 0.0
        return GravityCoefficients(
            name=self.name,
            gm_m3ps2=self.gm_m3ps2,
            ref_radius_m=self.ref_radius_m,
            n_max=n_max,
            m_max=m_max,
            tide_system=self.tide_system,
            cbar=cbar,
            sbar=sbar,
            source_sha256=self.source_sha256,
        )


def write_srgrav(path: Path, field: GravityCoefficients) -> None:
    """Write an SRGRAV v1 file. Output bytes are a pure function of the input."""
    name_bytes = field.name.encode("ascii")
    if len(name_bytes) > 15:
        raise DataFetchError(f"field name too long for SRGRAV v1: {field.name!r}")
    if field.tide_system not in TIDE_SYSTEM_CODES:
        raise DataFetchError(f"unknown tide system {field.tide_system!r}")
    if field.m_max > field.n_max:
        raise DataFetchError("m_max must not exceed n_max")
    header = struct.pack(
        _SRGRAV_HEADER_FMT,
        SRGRAV_MAGIC,
        SRGRAV_VERSION_MAJOR,
        SRGRAV_VERSION_MINOR,
        field.n_max,
        field.m_max,
        TIDE_SYSTEM_CODES[field.tide_system],
        0,  # reserved
        field.gm_m3ps2,
        field.ref_radius_m,
        name_bytes,
        bytes.fromhex(field.source_sha256),
        0,  # reserved
    )
    assert len(header) == _SRGRAV_HEADER_SIZE
    # Fixed interleaved (C, S) order, ascending n then ascending m
    # (srgrav_v1.md section 3); '<f8' keeps the block little-endian per the
    # format's fixed-endianness rule.
    pairs: list[float] = []
    for n in range(field.n_max + 1):
        for m in range(min(n, field.m_max) + 1):
            pairs.append(float(field.cbar[n, m]))
            pairs.append(float(field.sbar[n, m]))
    body = np.asarray(pairs, dtype="<f8").tobytes()
    path.write_bytes(header + body)


def read_srgrav(path: Path) -> GravityCoefficients:
    """Read an SRGRAV v1 file (reference reader mirroring the C++ loader)."""
    data = Path(path).read_bytes()
    if len(data) < _SRGRAV_HEADER_SIZE or data[:8] != SRGRAV_MAGIC:
        raise DataFetchError(f"{path}: not an SRGRAV file (bad magic or truncated header)")
    (
        _magic,
        major,
        minor,
        n_max,
        m_max,
        tide_code,
        _res0,
        gm,
        radius,
        name_raw,
        source_sha,
        _res1,
    ) = struct.unpack(_SRGRAV_HEADER_FMT, data[:_SRGRAV_HEADER_SIZE])
    if major != SRGRAV_VERSION_MAJOR:
        raise DataFetchError(
            f"{path}: SRGRAV major version {major} is not supported (reader "
            f"implements {SRGRAV_VERSION_MAJOR})"
        )
    del minor  # additive minor versions change nothing this reader consumes
    if tide_code not in TIDE_SYSTEM_NAMES:
        raise DataFetchError(f"{path}: unknown tide-system code {tide_code}")
    if m_max > n_max:
        raise DataFetchError(f"{path}: m_max {m_max} exceeds n_max {n_max}")
    n_entries = sum(min(n, m_max) + 1 for n in range(n_max + 1))
    expected = _SRGRAV_HEADER_SIZE + 16 * n_entries
    if len(data) != expected:
        raise DataFetchError(
            f"{path}: size {len(data)} does not match header (expected {expected})"
        )
    flat = np.frombuffer(data, dtype="<f8", count=2 * n_entries, offset=_SRGRAV_HEADER_SIZE)
    cbar = np.zeros((n_max + 1, n_max + 1), dtype=np.float64)
    sbar = np.zeros((n_max + 1, n_max + 1), dtype=np.float64)
    k = 0
    for n in range(n_max + 1):
        for m in range(min(n, m_max) + 1):
            cbar[n, m] = flat[k]
            sbar[n, m] = flat[k + 1]
            k += 2
    return GravityCoefficients(
        name=name_raw.rstrip(b"\x00").decode("ascii"),
        gm_m3ps2=gm,
        ref_radius_m=radius,
        n_max=n_max,
        m_max=m_max,
        tide_system=TIDE_SYSTEM_NAMES[tide_code],
        cbar=cbar,
        sbar=sbar,
        source_sha256=source_sha.hex(),
    )


# ---------------------------------------------------------------------------
# Source-format parsers: ICGEM gfc and PDS SHADR
# ---------------------------------------------------------------------------


def _to_float(token: str) -> float:
    # ICGEM files may carry Fortran 'D' exponents (EGM2008's degree-0 row is
    # literally "1.0d0"); binary64 conversion is otherwise one strtod.
    return float(token.replace("D", "E").replace("d", "e"))


def parse_icgem_gfc(
    path: Path, n_max_keep: int, source_sha256: str
) -> GravityCoefficients:
    """Parse an ICGEM-format gfc file, keeping degrees <= ``n_max_keep``.

    Implements the static-model subset of the ICGEM format (Ince et al.
    2019): header keys through ``end_of_head``, then ``gfc L M C S ...``
    rows. Time-variable rows (``gfct``/``trnd``/``acos``/``asin``) are
    rejected - the FR-5 fields are static models, and silently dropping
    time-variable terms would misrepresent a model that has them. Rows the
    source omits are filled per srgrav_v1.md section 3: C(0,0) = 1 exactly,
    zero elsewhere (fill applied by the caller-visible arrays being
    zero-initialized).
    """
    header: dict[str, str] = {}
    cbar = np.zeros((n_max_keep + 1, n_max_keep + 1), dtype=np.float64)
    sbar = np.zeros((n_max_keep + 1, n_max_keep + 1), dtype=np.float64)
    seen_00 = False
    in_data = False
    with open(path, "r", encoding="ascii", errors="strict") as fh:
        for line in fh:
            if not in_data:
                parts = line.split()
                if not parts:
                    continue
                if parts[0] == "end_of_head":
                    in_data = True
                    continue
                if len(parts) >= 2:
                    header[parts[0]] = parts[1]
                continue
            parts = line.split()
            if not parts:
                continue
            key = parts[0]
            if key != "gfc":
                raise DataFetchError(
                    f"{path}: unsupported coefficient key {key!r} (static 'gfc' "
                    f"rows only; time-variable models are not supported)"
                )
            n = int(parts[1])
            if n > n_max_keep:
                continue
            m = int(parts[2])
            if m > n:
                raise DataFetchError(f"{path}: order {m} exceeds degree {n}")
            cbar[n, m] = _to_float(parts[3])
            sbar[n, m] = _to_float(parts[4])
            if n == 0 and m == 0:
                seen_00 = True
    if not in_data:
        raise DataFetchError(f"{path}: no end_of_head marker; not an ICGEM gfc file")
    for req in ("modelname", "radius", "max_degree"):
        if req not in header:
            raise DataFetchError(f"{path}: missing required gfc header key {req!r}")
    gm_key = "earth_gravity_constant" if "earth_gravity_constant" in header else "gravity_constant"
    if gm_key not in header:
        raise DataFetchError(f"{path}: missing gravity-constant header key")
    norm = header.get("norm", "fully_normalized")
    if norm != "fully_normalized":
        raise DataFetchError(
            f"{path}: normalization {norm!r} is not supported (SRGRAV stores "
            f"fully normalized coefficients only)"
        )
    if int(header["max_degree"]) < n_max_keep:
        raise DataFetchError(
            f"{path}: source max_degree {header['max_degree']} is below the "
            f"requested repack degree {n_max_keep}"
        )
    if not seen_00:
        cbar[0, 0] = 1.0  # monopole carried by GM (srgrav_v1.md section 3)
    tide = header.get("tide_system", "unknown")
    if tide not in TIDE_SYSTEM_CODES:
        tide = "unknown"
    return GravityCoefficients(
        name=header["modelname"],
        gm_m3ps2=_to_float(header[gm_key]),
        ref_radius_m=_to_float(header["radius"]),
        n_max=n_max_keep,
        m_max=n_max_keep,
        tide_system=tide,
        cbar=cbar,
        sbar=sbar,
        source_sha256=source_sha256,
    )


def parse_pds_shadr(
    path: Path,
    n_max_keep: int,
    name: str,
    tide_system: str,
    source_sha256: str,
) -> GravityCoefficients:
    """Parse a PDS SHADR spherical-harmonics ASCII table (``*_sha.tab``).

    Layout per the PDS SHADR standard used by the GRAIL and MRO gravity
    deliveries: one header row ``R_km, GM_km3/s2, GM_sigma, degree, order,
    normalization_flag, ref_lon, ref_lat`` followed by ``n, m, C, S,
    sigma_C, sigma_S`` rows, comma-separated. The normalization flag must
    be 1 (fully normalized). GM and R convert to SI with exact power-of-ten
    scale factors recorded here (km -> m: 1e3; km^3/s^2 -> m^3/s^2: 1e9).
    The tide system is not encoded in the .tab file; the caller supplies it
    from the accompanying PDS label evidence.
    """
    cbar = np.zeros((n_max_keep + 1, n_max_keep + 1), dtype=np.float64)
    sbar = np.zeros((n_max_keep + 1, n_max_keep + 1), dtype=np.float64)
    seen_00 = False
    with open(path, "r", encoding="ascii", errors="strict") as fh:
        header_parts = fh.readline().split(",")
        if len(header_parts) < 8:
            raise DataFetchError(f"{path}: malformed SHADR header row")
        radius_m = _to_float(header_parts[0]) * 1.0e3
        gm_m3ps2 = _to_float(header_parts[1]) * 1.0e9
        max_degree = int(header_parts[3])
        norm_flag = int(header_parts[5])
        if norm_flag != 1:
            raise DataFetchError(
                f"{path}: normalization flag {norm_flag} is not supported "
                f"(SRGRAV stores fully normalized coefficients only)"
            )
        if max_degree < n_max_keep:
            raise DataFetchError(
                f"{path}: source degree {max_degree} is below the requested "
                f"repack degree {n_max_keep}"
            )
        for line in fh:
            parts = line.split(",")
            if len(parts) < 4 or not parts[0].strip():
                continue
            n = int(parts[0])
            if n > n_max_keep:
                # Rows are ordered by ascending degree in the PDS deliveries,
                # but continue (not break) so the parse never depends on it.
                continue
            m = int(parts[1])
            if m > n:
                raise DataFetchError(f"{path}: order {m} exceeds degree {n}")
            cbar[n, m] = _to_float(parts[2])
            sbar[n, m] = _to_float(parts[3])
            if n == 0 and m == 0:
                seen_00 = True
    if not seen_00:
        cbar[0, 0] = 1.0  # monopole carried by GM (srgrav_v1.md section 3)
    if tide_system not in TIDE_SYSTEM_CODES:
        raise DataFetchError(f"unknown tide system {tide_system!r}")
    return GravityCoefficients(
        name=name,
        gm_m3ps2=gm_m3ps2,
        ref_radius_m=radius_m,
        n_max=n_max_keep,
        m_max=n_max_keep,
        tide_system=tide_system,
        cbar=cbar,
        sbar=sbar,
        source_sha256=source_sha256,
    )


def read_coeffs_csv(path: Path) -> GravityCoefficients:
    """Read a committed coefficient-excerpt CSV (tests/golden/gravity/).

    Format: '#'-prefixed provenance comments, a ``key = value`` metadata
    block inside the comments, then ``n,m,cbar,sbar`` rows with full-
    precision ``repr`` decimals. The excerpts exist so goldens and pytest
    can rebuild bit-identical SRGRAV fixtures offline.
    """
    meta: dict[str, str] = {}
    rows: list[tuple[int, int, float, float]] = []
    with open(path, "r", encoding="ascii") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            if line.startswith("#"):
                body = line.lstrip("#").strip()
                if "=" in body:
                    key, _, value = body.partition("=")
                    meta[key.strip()] = value.strip()
                continue
            if line.startswith("n,"):
                continue  # column header row
            n_s, m_s, c_s, s_s = line.split(",")
            rows.append((int(n_s), int(m_s), float(c_s), float(s_s)))
    for req in ("name", "gm_m3ps2", "ref_radius_m", "n_max", "m_max", "tide_system", "source_sha256"):
        if req not in meta:
            raise DataFetchError(f"{path}: excerpt CSV missing metadata key {req!r}")
    n_max = int(meta["n_max"])
    m_max = int(meta["m_max"])
    cbar = np.zeros((n_max + 1, n_max + 1), dtype=np.float64)
    sbar = np.zeros((n_max + 1, n_max + 1), dtype=np.float64)
    for n, m, c, s in rows:
        cbar[n, m] = c
        sbar[n, m] = s
    return GravityCoefficients(
        name=meta["name"],
        gm_m3ps2=float(meta["gm_m3ps2"]),
        ref_radius_m=float(meta["ref_radius_m"]),
        n_max=n_max,
        m_max=m_max,
        tide_system=meta["tide_system"],
        cbar=cbar,
        sbar=sbar,
        source_sha256=meta["source_sha256"],
    )


# ---------------------------------------------------------------------------
# FR-5 gravity datasets: sources, pins, and repack degrees
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GravityDatasetSpec:
    dataset: str  # CLI name
    field_name: str  # SRGRAV header name
    body: str
    url: str
    source_filename: str
    source_sha256: str
    source_format: str  # "icgem_gfc" | "pds_shadr"
    n_repack: int  # FR-5 truncation degree (= order; the fields are square)
    tide_system: str | None  # None: take from the gfc header
    citation: str


# Pin policy (same as DE440S_SHA256): the publishers do not distribute
# checksums next to these files, so each pin records the exact bytes this
# project validated - the committed golden accelerations under
# tests/golden/gravity/ were generated from excerpts of THESE files and
# cross-checked against pyshtools (see tests/golden/gravity/manifest.toml).
# A future download that fails its pin is a different file and must be
# re-validated, not silently accepted. The MRO120F pin is independently
# corroborated: pyshtools 4.14.1 pins the identical SHA-256 for the same
# PDS URL in its dataset registry.
GRAVITY_DATASETS = {
    "egm2008": GravityDatasetSpec(
        dataset="egm2008",
        field_name="EGM2008",
        body="earth",
        # ICGEM (GFZ) getmodel URL for EGM2008; icgem.gfz-potsdam.de now
        # redirects to icgem.gfz.de, so the current host is recorded.
        url=(
            "https://icgem.gfz.de/getmodel/gfc/"
            "c50128797a9cb62e936337c890e4425f03f0461d7329b09a8cc8561504465340/EGM2008.gfc"
        ),
        source_filename="EGM2008.gfc",
        source_sha256="ab5b524da073e63b5bdceb7ca47a0de07a26dd44a1c5798f39fc98dc80af70fd",
        source_format="icgem_gfc",
        n_repack=70,
        tide_system=None,  # gfc header states tide_free
        citation=(
            "Pavlis, Holmes, Kenyon, and Factor, 'The development and "
            "evaluation of the Earth Gravitational Model 2008 (EGM2008)', "
            "JGR 117, B04406, 2012"
        ),
    ),
    "grgm1200a": GravityDatasetSpec(
        dataset="grgm1200a",
        field_name="GRGM1200A",
        body="moon",
        # NASA PDS Geosciences Node archive of record for the GRAIL GSFC
        # gravity deliveries (ICGEM does not carry GRGM1200A).
        url=(
            "https://pds-geosciences.wustl.edu/grail/grail-l-lgrs-5-rdr-v1/"
            "grail_1001/shadr/gggrx_1200a_sha.tab"
        ),
        source_filename="gggrx_1200a_sha.tab",
        source_sha256="fa04c3dce9376948ad243f3df74144e2602f12d183ea4d179604ed0a79da7ded",
        source_format="pds_shadr",
        n_repack=120,
        # The PDS label (gggrx_1200a_sha.lbl) gives the Love number used but
        # does not state a permanent-tide convention for C(2,0); recorded
        # honestly as not stated.
        tide_system="unknown",
        citation=(
            "Lemoine et al., 'GRGM900C: A degree 900 lunar gravity model "
            "from GRAIL primary and extended mission data', GRL 41, "
            "3382-3389, 2014 (the reference the GRGM1200A PDS label "
            "designates); Goossens et al., JGR Planets 125, e2019JE006086, 2020"
        ),
    ),
    "mro120f": GravityDatasetSpec(
        dataset="mro120f",
        field_name="MRO120F",
        body="mars",
        # NASA PDS Geosciences Node archive of record for the JPL MRO
        # radio-science gravity deliveries.
        url=(
            "https://pds-geosciences.wustl.edu/mro/mro-m-rss-5-sdp-v1/"
            "mrors_1xxx/data/shadr/jgmro_120f_sha.tab"
        ),
        source_filename="jgmro_120f_sha.tab",
        source_sha256="ddd3de9c30d75879fe37aa17a1149e7c96c141c095962954cb7ea865a2c025b6",
        source_format="pds_shadr",
        n_repack=80,
        # The PDS label states the degree-2 coefficients exclude the
        # permanent tide.
        tide_system="tide_free",
        citation=(
            "Konopliv et al., 'Detection of the Chandler Wobble of Mars "
            "From Orbiting Spacecraft', GRL 47, e2020GL090568, 2020"
        ),
    ),
}


def fetch_gravity(dataset: str, data_dir: Path) -> Path:
    """Fetch and repack one FR-5 gravity field; idempotent. Returns the repack path."""
    spec = GRAVITY_DATASETS[dataset]
    data_dir = Path(data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    source_path = data_dir / spec.source_filename
    out_path = data_dir / f"{spec.dataset}_n{spec.n_repack}.srgrav"
    manifest_path = data_dir / f"{spec.dataset}_manifest.json"

    source_sha = _ensure_source(spec.url, spec.source_sha256, source_path)

    if out_path.is_file() and manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            manifest = {}
        recorded = manifest.get("repack_sha256")
        if recorded and _sha256(out_path) == recorded:
            print(f"{out_path.name}: present, SHA-256 verified ({recorded[:12]}...)")
            print(f"data fetch {dataset}: verified, nothing to do ({out_path})")
            return out_path

    if spec.source_format == "icgem_gfc":
        field = parse_icgem_gfc(source_path, spec.n_repack, source_sha)
        field.name = spec.field_name
    else:
        field = parse_pds_shadr(
            source_path, spec.n_repack, spec.field_name, spec.tide_system or "unknown", source_sha
        )
    if spec.tide_system is not None:
        field.tide_system = spec.tide_system
    write_srgrav(out_path, field)
    repack_sha = _sha256(out_path)
    manifest_path.write_text(
        json.dumps(
            {
                "dataset": spec.dataset,
                "format": "SRGRAV",
                "format_version": f"{SRGRAV_VERSION_MAJOR}.{SRGRAV_VERSION_MINOR}",
                "body": spec.body,
                "field_name": spec.field_name,
                "citation": spec.citation,
                "sources": [{"url": spec.url, "sha256": source_sha}],
                "repack_file": out_path.name,
                "repack_sha256": repack_sha,
                "n_max": field.n_max,
                "m_max": field.m_max,
                "gm_m3ps2": field.gm_m3ps2,
                "ref_radius_m": field.ref_radius_m,
                "tide_system": field.tide_system,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    size_kib = out_path.stat().st_size / 1024.0
    print(
        f"repacked {spec.field_name} to {field.n_max}x{field.m_max}, "
        f"{size_kib:.0f} KiB -> {out_path}"
    )
    print(f"data fetch {dataset}: complete ({out_path})")
    return out_path


def cli_fetch(dataset: str, data_dir: str) -> int:
    """CLI entry: ``star data fetch <dataset>``. Returns the exit code."""
    known = ["de440s", *sorted(GRAVITY_DATASETS)]
    if dataset not in known:
        print(
            f"star data fetch: unknown dataset {dataset!r}; available: "
            f"{', '.join(known)}.",
            file=sys.stderr,
        )
        return 2
    try:
        if dataset == "de440s":
            fetch_de440s(Path(data_dir))
        else:
            fetch_gravity(dataset, Path(data_dir))
    except DataFetchError as exc:
        print(f"star data fetch: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"star data fetch: {exc}", file=sys.stderr)
        return 1
    return 0
