"""``star data fetch`` implementation: DE440s download and repack (D-8, FR-4).

One-time maintainer-side pipeline: download the JPL DE440s planetary SPK and
the DE440 lunar principal-axis binary PCK, verify both against pinned SHA-256
values, and repack the segments star_reacher needs (Sun, EMB, Earth, Moon,
Venus barycenter, Mars barycenter, Jupiter barycenter, lunar libration
angles; 2020-01-01 through 2060-01-01 TDB) into one small SREPH v1 binary
file that the C++ core loads directly. The Chebyshev coefficients are copied
verbatim from the source kernels - never refitted - so the repack inherits
DE440 accuracy exactly (format specification: ``docs/formats/sreph_v1.md``).

The module also carries a pure-Python SREPH reader and Chebyshev evaluator.
It is the executable specification of the C++ evaluator
(``cpp/src/ephemeris.cpp``): both implement the identical operation sequence,
so on IEEE-754 double hardware with FMA contraction disabled (D-10 build
flags) they produce bit-identical outputs. The committed bit-level golden
vectors under ``tests/golden/ephemeris/`` are generated by this evaluator.

Everything here runs before t0 (D-2 boundary rule): network, text, and
checksum handling stay in Python; the core only ever sees the binary SREPH
file.
"""

from __future__ import annotations

import hashlib
import json
import math
import struct
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Source kernels and their pinned checksums
# ---------------------------------------------------------------------------

# JPL Solar System Dynamics distribution point for the DE440s planetary
# ephemeris SPK (Park, Folkner, Williams, and Boggs, "The JPL Planetary and
# Lunar Ephemerides DE440 and DE441", AJ 161:105, 2021). DE440s is the
# short-span (1849-2150) excerpt of DE440 published by JPL alongside it.
DE440S_URL = "https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de440s.bsp"
DE440S_SIZE_BYTES = 32726016
# SHA-256 of de440s.bsp as downloaded from DE440S_URL on 2026-07-02. JPL does
# not publish a checksum for this file, so the pin records the exact bytes
# this project validated: the repack of THIS file matches JPL Horizons
# geometric states to well under 1 m at 21 epochs spanning 2020-2060 (see
# tests/golden/ephemeris/manifest.toml and full_span_validation.md). A future
# download that fails this pin is a different file and must be re-validated,
# not silently accepted.
DE440S_SHA256 = "c1c7feeab882263fc493a9d5a5b2ddd71b54826cdf65d8d17a76126b260a49f2"

# NAIF generic-kernels distribution point for the DE440 lunar principal-axis
# orientation binary PCK (Euler angles of the Moon PA frame, i.e. the lunar
# librations integrated with DE440; same Park et al. 2021 reference).
MOON_PA_URL = (
    "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/moon_pa_de440_200625.bpc"
)
MOON_PA_SIZE_BYTES = 12863488
# SHA-256 of moon_pa_de440_200625.bpc as downloaded from MOON_PA_URL on
# 2026-07-02; same pin policy as DE440S_SHA256 (validated content, recorded
# bytes). Libration output from the repack of THIS file matches jplephem's
# independent evaluation of the same kernel (tests/golden/ephemeris/).
MOON_PA_SHA256 = "60cd55aa401ea2ea97360636f567554bfe4e37bb829f901b4460a455dfaf783f"

# ---------------------------------------------------------------------------
# Repack span (D-8: 2020-2060) in TDB seconds since J2000 TDB
# ---------------------------------------------------------------------------

# J2000 is JD 2451545.0 TDB (2000-01-01T12:00:00 TDB). Both bounds fall on
# TDB midnights, which are exactly representable in binary64 both as Julian
# dates (half-integers) and as seconds since J2000 (multiples of 43200), so
# no quantization enters the span arithmetic.
SPAN_START_TDB_S = 631108800.0  # 2020-01-01T00:00:00 TDB = JD 2458849.5
SPAN_END_TDB_S = 1893412800.0  # 2060-01-01T00:00:00 TDB = JD 2473459.5

# Segment kinds in the SREPH file (docs/formats/sreph_v1.md section 4).
KIND_POSITION_KM = 0  # SPK Type 2: position Chebyshev coefficients [km]
KIND_ANGLES_RAD = 1  # PCK Type 2: Euler-angle Chebyshev coefficients [rad]

# Bodies repacked from de440s.bsp: (name, NAIF target, NAIF center).
# Moon and Earth are carried relative to the Earth-Moon barycenter exactly as
# DE440 stores them; the geocentric Moon state is composed at evaluation time
# as moon - earth (both EMB-relative), never re-fitted.
SPK_BODIES = (
    ("sun", 10, 0),
    ("emb", 3, 0),
    ("earth", 399, 3),
    ("moon", 301, 3),
    ("venus_bary", 2, 0),
    ("mars_bary", 4, 0),
    ("jupiter_bary", 5, 0),
)
# Lunar librations from the binary PCK: body 31008 is the NAIF class ID of
# the MOON_PA_DE440 frame; its "center" slot carries the PCK reference frame
# (1 = J2000). The three components are the 3-1-3 Euler angles phi, theta,
# psi of the lunar principal-axis frame relative to the ICRF equator.
LIBRATION_NAME = "moon_librations"
LIBRATION_BODY = 31008
LIBRATION_FRAME = 1

SREPH_MAGIC = b"SREPH\x00\r\n"  # NUL + CRLF tripwire, mirroring SRLOG (D-11)
SREPH_VERSION_MAJOR = 1
SREPH_VERSION_MINOR = 0
_HEADER_SIZE = 96
_DIR_ENTRY_SIZE = 64

REPACK_FILENAME = "de440s_2020_2060.sreph"
MANIFEST_FILENAME = "de440s_manifest.json"


class DataFetchError(Exception):
    """A fetch, checksum, or repack step failed; the message says which."""


# ---------------------------------------------------------------------------
# SREPH v1 container
# ---------------------------------------------------------------------------


@dataclass
class SrephSegment:
    """One repacked Chebyshev segment (docs/formats/sreph_v1.md section 4)."""

    name: str
    target: int
    center: int
    kind: int
    init_tdb_s: float
    intlen_s: float
    coeffs: np.ndarray  # (n_records, 3, n_coeffs) float64, verbatim from DAF

    @property
    def n_records(self) -> int:
        return int(self.coeffs.shape[0])

    @property
    def n_coeffs(self) -> int:
        return int(self.coeffs.shape[2])

    @property
    def end_tdb_s(self) -> float:
        return self.init_tdb_s + self.n_records * self.intlen_s


def write_sreph(
    path: Path,
    segments: list[SrephSegment],
    source_spk_sha256: str,
    source_pck_sha256: str,
) -> None:
    """Write an SREPH v1 file. Output bytes are a pure function of the inputs."""
    dir_bytes = bytearray()
    data_bytes = bytearray()
    data_offset = _HEADER_SIZE + _DIR_ENTRY_SIZE * len(segments)
    for seg in segments:
        name_bytes = seg.name.encode("ascii")
        if len(name_bytes) > 15:
            raise DataFetchError(f"segment name too long for SREPH v1: {seg.name!r}")
        if seg.coeffs.shape[1] != 3 or seg.coeffs.dtype != np.float64:
            raise DataFetchError(f"segment {seg.name!r}: coefficients must be (n,3,m) float64")
        dir_bytes += struct.pack(
            "<16sIIIIddIIQ",
            name_bytes,
            seg.target,
            seg.center,
            seg.kind,
            seg.n_coeffs,
            seg.init_tdb_s,
            seg.intlen_s,
            seg.n_records,
            0,  # reserved
            data_offset + len(data_bytes),
        )
        # '<' packing plus float64 tobytes keeps the file little-endian on
        # every host, per the format's fixed-endianness rule.
        data_bytes += np.ascontiguousarray(seg.coeffs, dtype="<f8").tobytes()
    span_start = max(seg.init_tdb_s for seg in segments)
    span_end = min(seg.end_tdb_s for seg in segments)
    header = struct.pack(
        "<8sHHIdd32s32s",
        SREPH_MAGIC,
        SREPH_VERSION_MAJOR,
        SREPH_VERSION_MINOR,
        len(segments),
        span_start,
        span_end,
        bytes.fromhex(source_spk_sha256),
        bytes.fromhex(source_pck_sha256),
    )
    assert len(header) == _HEADER_SIZE
    path.write_bytes(header + bytes(dir_bytes) + bytes(data_bytes))


@dataclass
class SrephFile:
    """Parsed SREPH v1 file (reference reader mirroring the C++ loader)."""

    span_start_tdb_s: float
    span_end_tdb_s: float
    source_spk_sha256: str
    source_pck_sha256: str
    segments: list[SrephSegment]

    def segments_named(self, name: str) -> list[SrephSegment]:
        found = [s for s in self.segments if s.name == name]
        if not found:
            names = sorted({s.name for s in self.segments})
            raise KeyError(f"sreph: unknown body {name!r}; available: {names}")
        return found

    def segment_for(self, name: str, tdb_s: float) -> SrephSegment:
        candidates = self.segments_named(name)
        for seg in candidates:
            if seg.init_tdb_s <= tdb_s <= seg.end_tdb_s:
                return seg
        raise ValueError(
            f"sreph: epoch {tdb_s!r} s TDB is outside every stored segment of "
            f"{name!r}; refusing to extrapolate"
        )


def read_sreph(path: Path) -> SrephFile:
    data = Path(path).read_bytes()
    if len(data) < _HEADER_SIZE or data[:8] != SREPH_MAGIC:
        raise DataFetchError(f"{path}: not an SREPH file (bad magic or truncated header)")
    (major, minor, seg_count, span_start, span_end, spk_sha, pck_sha) = struct.unpack(
        "<HHIdd32s32s", data[8:_HEADER_SIZE]
    )
    if major != SREPH_VERSION_MAJOR:
        raise DataFetchError(
            f"{path}: SREPH major version {major} is not supported (reader implements "
            f"{SREPH_VERSION_MAJOR})"
        )
    del minor  # additive minor versions change nothing this reader consumes
    segments: list[SrephSegment] = []
    for i in range(seg_count):
        entry_off = _HEADER_SIZE + i * _DIR_ENTRY_SIZE
        entry = data[entry_off : entry_off + _DIR_ENTRY_SIZE]
        if len(entry) != _DIR_ENTRY_SIZE:
            raise DataFetchError(f"{path}: truncated segment directory")
        (name_raw, target, center, kind, n_coeffs, init, intlen, n_records, _res, off) = (
            struct.unpack("<16sIIIIddIIQ", entry)
        )
        nbytes = n_records * 3 * n_coeffs * 8
        if off + nbytes > len(data):
            raise DataFetchError(f"{path}: segment {i} coefficient block runs past EOF")
        coeffs = np.frombuffer(data, dtype="<f8", count=n_records * 3 * n_coeffs, offset=off)
        segments.append(
            SrephSegment(
                name=name_raw.rstrip(b"\x00").decode("ascii"),
                target=target,
                center=center,
                kind=kind,
                init_tdb_s=init,
                intlen_s=intlen,
                coeffs=coeffs.reshape(n_records, 3, n_coeffs),
            )
        )
    return SrephFile(
        span_start_tdb_s=span_start,
        span_end_tdb_s=span_end,
        source_spk_sha256=spk_sha.hex(),
        source_pck_sha256=pck_sha.hex(),
        segments=segments,
    )


# ---------------------------------------------------------------------------
# Reference Chebyshev evaluator (the executable spec of cpp/src/ephemeris.cpp)
# ---------------------------------------------------------------------------


def evaluate_segment(seg: SrephSegment, tdb_s: float) -> tuple[list[float], list[float]]:
    """Evaluate one segment at ``tdb_s``; returns (values, rates) in native units.

    Kind 0 segments yield km and km/s; kind 1 yields rad and rad/s. The
    operation sequence below is mirrored statement-for-statement by
    ``star::Ephemeris`` in ``cpp/src/ephemeris.cpp`` (labels
    eq:ephemeris:timescale, eq:ephemeris:recurrence, eq:ephemeris:series in
    the math library chapter); any change here is a change to the bit-level
    golden contract and must be made in both places.
    """
    if not (seg.init_tdb_s <= tdb_s <= seg.end_tdb_s):
        raise ValueError(f"epoch {tdb_s!r} outside segment [{seg.init_tdb_s}, {seg.end_tdb_s}]")
    # Record selection: the boundary epoch between records k-1 and k belongs
    # to record k; the segment's final epoch (which would select record n)
    # clamps to the last record and evaluates at x = +1 exactly.
    k = math.floor((tdb_s - seg.init_tdb_s) / seg.intlen_s)
    n = seg.n_records
    if k >= n:
        k = n - 1
    if k < 0:
        k = 0
    # eq:ephemeris:timescale
    t0 = seg.init_tdb_s + k * seg.intlen_s
    x = 2.0 * (tdb_s - t0) / seg.intlen_s - 1.0
    ncoef = seg.n_coeffs
    T = [0.0] * ncoef
    dT = [0.0] * ncoef
    T[0] = 1.0
    if ncoef > 1:
        T[1] = x
        dT[1] = 1.0
    # eq:ephemeris:recurrence
    for j in range(2, ncoef):
        T[j] = 2.0 * x * T[j - 1] - T[j - 2]
        dT[j] = 2.0 * T[j - 1] + 2.0 * x * dT[j - 1] - dT[j - 2]
    values: list[float] = []
    rates: list[float] = []
    rec = seg.coeffs[k]
    # eq:ephemeris:series - fixed ascending accumulation order (D-10)
    for comp in range(3):
        acc = 0.0
        acc_d = 0.0
        for j in range(ncoef):
            c = float(rec[comp][j])
            acc = acc + c * T[j]
            acc_d = acc_d + c * dT[j]
        values.append(acc)
        rates.append(acc_d * (2.0 / seg.intlen_s))
    return values, rates


def evaluate_state_m(
    sreph: SrephFile, name: str, tdb_s: float
) -> tuple[list[float], list[float]]:
    """Position [m] and velocity [m/s] of ``name`` relative to its center."""
    seg = sreph.segment_for(name, tdb_s)
    if seg.kind != KIND_POSITION_KM:
        raise ValueError(f"{name!r} is not a position segment")
    v, r = evaluate_segment(seg, tdb_s)
    return [c * 1000.0 for c in v], [c * 1000.0 for c in r]


def evaluate_librations(sreph: SrephFile, tdb_s: float) -> tuple[list[float], list[float]]:
    """Lunar libration Euler angles [rad] and rates [rad/s]."""
    seg = sreph.segment_for(LIBRATION_NAME, tdb_s)
    if seg.kind != KIND_ANGLES_RAD:
        raise ValueError(f"{LIBRATION_NAME!r} is not an angle segment")
    return evaluate_segment(seg, tdb_s)


# ---------------------------------------------------------------------------
# DAF Type 2 extraction (verbatim coefficients)
# ---------------------------------------------------------------------------


def _extract_type2(daf, start_i: int, end_i: int) -> tuple[float, float, np.ndarray]:
    """Return (init, intlen, coeffs (n,3,m)) copied verbatim from a DAF array.

    SPK Type 2 and binary-PCK Type 2 share this layout (SPK Required Reading,
    NAIF): N records of RSIZE doubles - MID, RADIUS, then the Chebyshev
    coefficients of the three components in ascending order - followed by a
    four-double trailer INIT, INTLEN, RSIZE, N. MID and RADIUS are dropped:
    they are exactly INIT + (k + 1/2) * INTLEN and INTLEN / 2 for every DE
    Type 2 segment, so the retained INIT/INTLEN reproduce them.
    """
    trailer = np.array(daf.read_array(end_i - 3, end_i), dtype=np.float64)
    init, intlen, rsize, n = (float(trailer[0]), float(trailer[1]), int(trailer[2]), int(trailer[3]))
    ncoef = (rsize - 2) // 3
    if rsize != 2 + 3 * ncoef:
        raise DataFetchError(f"unsupported Type 2 record size {rsize}")
    raw = np.array(daf.read_array(start_i, end_i - 4), dtype=np.float64)
    if raw.size != n * rsize:
        raise DataFetchError(f"Type 2 payload size {raw.size} != N*RSIZE = {n * rsize}")
    records = raw.reshape(n, rsize)
    # Sanity-pin the redundant bookkeeping we drop, so a kernel that violated
    # the constant-interval assumption could never repack silently wrong.
    if not (
        records[0, 0] == init + 0.5 * intlen and records[0, 1] == 0.5 * intlen
    ):
        raise DataFetchError("Type 2 MID/RADIUS do not match INIT/INTLEN")
    return init, intlen, records[:, 2:].reshape(n, 3, ncoef).copy()


def _trim_records(
    init: float, intlen: float, coeffs: np.ndarray, t_lo: float, t_hi: float
) -> tuple[float, np.ndarray]:
    """Keep the whole records covering [t_lo, t_hi]; never split a record."""
    n = coeffs.shape[0]
    k_lo = int(math.floor((t_lo - init) / intlen))
    k_hi = int(math.floor((t_hi - init) / intlen))
    if k_hi * intlen + init == t_hi:
        k_hi -= 1  # t_hi on a boundary: the record ending there covers it
    if k_lo < 0 or k_hi >= n:
        raise DataFetchError(
            f"requested span [{t_lo}, {t_hi}] s TDB exceeds source segment coverage"
        )
    return init + k_lo * intlen, coeffs[k_lo : k_hi + 1].copy()


def repack(spk_path: Path, pck_path: Path, out_path: Path) -> SrephFile:
    """Repack the D-8 body set from the source kernels into ``out_path``."""
    # Imported here, not module-level: jplephem is a runtime dependency, but
    # only this maintainer-side path needs it (D-12 data-prep role).
    from jplephem.pck import PCK
    from jplephem.spk import SPK

    segments: list[SrephSegment] = []
    spk = SPK.open(str(spk_path))
    try:
        by_key = {(s.target, s.center): s for s in spk.segments}
        for name, target, center in SPK_BODIES:
            src = by_key.get((target, center))
            if src is None:
                raise DataFetchError(
                    f"{spk_path}: no segment for target {target} center {center} ({name})"
                )
            if src.data_type != 2:
                raise DataFetchError(f"{spk_path}: segment {name} is not SPK Type 2")
            init, intlen, coeffs = _extract_type2(spk.daf, src.start_i, src.end_i)
            init_trim, coeffs_trim = _trim_records(
                init, intlen, coeffs, SPAN_START_TDB_S, SPAN_END_TDB_S
            )
            segments.append(
                SrephSegment(name, target, center, KIND_POSITION_KM, init_trim, intlen, coeffs_trim)
            )
    finally:
        spk.close()

    pck = PCK.open(str(pck_path))
    try:
        lib_segments = [s for s in pck.segments if s.body == LIBRATION_BODY and s.data_type == 2]
        covering = [
            s
            for s in lib_segments
            if s.initial_second <= SPAN_START_TDB_S and s.final_second >= SPAN_END_TDB_S
        ]
        if not covering:
            raise DataFetchError(
                f"{pck_path}: no Type 2 segment for body {LIBRATION_BODY} covers the repack span"
            )
        src = covering[0]
        init, intlen, coeffs = _extract_type2(pck.daf, src.start_i, src.end_i)
        init_trim, coeffs_trim = _trim_records(
            init, intlen, coeffs, SPAN_START_TDB_S, SPAN_END_TDB_S
        )
        segments.append(
            SrephSegment(
                LIBRATION_NAME,
                LIBRATION_BODY,
                LIBRATION_FRAME,
                KIND_ANGLES_RAD,
                init_trim,
                intlen,
                coeffs_trim,
            )
        )
    finally:
        pck.daf.file.close()

    write_sreph(out_path, segments, _sha256(spk_path), _sha256(pck_path))
    return read_sreph(out_path)


# ---------------------------------------------------------------------------
# Fetch orchestration
# ---------------------------------------------------------------------------


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _download(url: str, dest: Path) -> None:
    print(f"downloading {url} -> {dest} ...", flush=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    with urllib.request.urlopen(url) as resp, open(tmp, "wb") as out:
        while True:
            chunk = resp.read(1 << 20)
            if not chunk:
                break
            out.write(chunk)
    tmp.replace(dest)


def _ensure_source(url: str, expected_sha256: str, dest: Path) -> str:
    """Download ``dest`` unless a checksum-verified copy is already present."""
    if dest.is_file():
        got = _sha256(dest)
        if got == expected_sha256:
            print(f"{dest.name}: present, SHA-256 verified ({got[:12]}...)")
            return got
        raise DataFetchError(
            f"{dest}: SHA-256 mismatch.\n  expected {expected_sha256}\n  got      {got}\n"
            f"The file on disk is not the validated kernel. Delete it to re-download, "
            f"or update the pinned hash only after re-running the Horizons validation "
            f"(tests/golden/ephemeris/generate.py)."
        )
    _download(url, dest)
    got = _sha256(dest)
    if got != expected_sha256:
        raise DataFetchError(
            f"{dest}: downloaded file fails the SHA-256 pin.\n"
            f"  expected {expected_sha256}\n  got      {got}\n"
            f"JPL may have republished the kernel; do not use it until it is "
            f"re-validated against Horizons and the pin is updated."
        )
    print(f"{dest.name}: downloaded, SHA-256 verified ({got[:12]}...)")
    return got


def fetch_de440s(data_dir: Path) -> Path:
    """Fetch and repack DE440s; idempotent. Returns the repack path."""
    data_dir = Path(data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    spk_path = data_dir / "de440s.bsp"
    pck_path = data_dir / "moon_pa_de440_200625.bpc"
    out_path = data_dir / REPACK_FILENAME
    manifest_path = data_dir / MANIFEST_FILENAME

    spk_sha = _ensure_source(DE440S_URL, DE440S_SHA256, spk_path)
    pck_sha = _ensure_source(MOON_PA_URL, MOON_PA_SHA256, pck_path)

    if out_path.is_file() and manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            manifest = {}
        recorded = manifest.get("repack_sha256")
        if recorded and _sha256(out_path) == recorded:
            print(f"{out_path.name}: present, SHA-256 verified ({recorded[:12]}...)")
            print(f"data fetch de440s: verified, nothing to do ({out_path})")
            return out_path

    sreph = repack(spk_path, pck_path, out_path)
    repack_sha = _sha256(out_path)
    manifest_path.write_text(
        json.dumps(
            {
                "dataset": "de440s",
                "format": "SREPH",
                "format_version": f"{SREPH_VERSION_MAJOR}.{SREPH_VERSION_MINOR}",
                "sources": [
                    {"url": DE440S_URL, "sha256": spk_sha},
                    {"url": MOON_PA_URL, "sha256": pck_sha},
                ],
                "repack_file": out_path.name,
                "repack_sha256": repack_sha,
                "span_tdb_s": [sreph.span_start_tdb_s, sreph.span_end_tdb_s],
                "segments": [
                    {
                        "name": s.name,
                        "target": s.target,
                        "center": s.center,
                        "kind": s.kind,
                        "records": s.n_records,
                        "coefficients": s.n_coeffs,
                        "interval_s": s.intlen_s,
                    }
                    for s in sreph.segments
                ],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    size_kib = out_path.stat().st_size / 1024.0
    print(
        f"repacked {len(sreph.segments)} segments, span "
        f"[{sreph.span_start_tdb_s:.0f}, {sreph.span_end_tdb_s:.0f}] s TDB, "
        f"{size_kib:.0f} KiB -> {out_path}"
    )
    print(f"data fetch de440s: complete ({out_path})")
    return out_path


def cli_fetch(dataset: str, data_dir: str) -> int:
    """CLI entry: ``star data fetch <dataset>``. Returns the exit code."""
    if dataset != "de440s":
        print(
            f"star data fetch: unknown dataset {dataset!r}; available: de440s.",
            file=sys.stderr,
        )
        return 2
    try:
        fetch_de440s(Path(data_dir))
    except DataFetchError as exc:
        print(f"star data fetch: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"star data fetch: {exc}", file=sys.stderr)
        return 1
    return 0
