"""Independent Allan-variance reference for Phase 6 exit criterion 1.

Part of the Phase 6 independent-reference set (``tests/refs/manifest.toml``):
written from Chapter ``ch:sensors-imu`` and from IEEE Std 952 as cited there,
with no reference to the core IMU implementation it gates. Exit criterion 1
requires that Allan-deviation analysis of a 1e4 s static IMU record recover the
configured angular-random-walk and bias-instability coefficients to within
+/- 10 %.

The estimator is validated here against SYNTHETIC signals whose coefficients are
known exactly by construction -- generated by :func:`synthesize_static_record`
from the chapter's own error-chain equations. That is the ground truth: an
estimator that recovers known coefficients from a signal it did not generate the
statistics of is demonstrably correct independently of any sensor
implementation. Nothing here depends on the compiled core.

Contents, all with their chapter equation labels:

* :func:`overlapping_allan_variance` -- ``eq:imu:oadev``, the maximally
  overlapped estimator on the accumulated-angle (phase) record.
* :func:`white_noise_adev` -- ``eq:imu:whiteslope``, ``sigma(tau) = N/sqrt(tau)``.
* :func:`gauss_markov_allan_variance` -- ``eq:imu:gmadev``, the closed form for a
  first-order Gauss-Markov rate process.
* :func:`gauss_markov_peak` -- ``eq:imu:gmpeak``, the interior maximum located
  numerically rather than copied from the chapter's quoted constants, so the
  quoted values are checked rather than assumed.
* :func:`bias_instability_from_sigma_gm` / :func:`sigma_gm_from_bias_instability`
  -- ``eq:imu:bi`` and the preset mapping ``eq:imu:presetmap``.
* :func:`quantization_adev` -- ``eq:imu:quantadev``, ``sigma(tau) = q/(2 tau)``.
* :func:`recover_coefficients` -- the section ``sec:imu:recovery`` procedure,
  equations ``eq:imu:recovery`` and ``eq:imu:recoverybi``.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

# Equation eq:imu:bi: the classical flicker-noise flat-region relation
# sigma_min = sqrt(2 ln2 / pi) B. Computed rather than transcribed as 0.664 so
# the constant carries full precision and its provenance is visible.
BIAS_INSTABILITY_FACTOR = np.sqrt(2.0 * np.log(2.0) / np.pi)

# Data-sheet unit conversions, exact by definition (ch:sensors-imu, after
# equation eq:imu:arw).
DEG_PER_SQRT_HOUR_TO_RAD_PER_SQRT_S = (np.pi / 180.0) / 60.0
DEG_PER_HOUR_TO_RAD_PER_S = (np.pi / 180.0) / 3600.0


def overlapping_allan_variance(
    phase: np.ndarray, dt_s: float, m: int
) -> float:
    """Overlapping Allan variance at cluster time ``tau = m dt``, ``eq:imu:oadev``.

    ``phase`` is the accumulated-angle record ``theta_n = sum_{k<=n} dtheta_k``
    with ``theta_0 = 0`` prepended, so ``len(phase) = N_theta``. The estimator is

        var(tau) = 1 / (2 tau**2 (N - 2m)) sum_{n=0}^{N-2m-1}
                   (theta_{n+2m} - 2 theta_{n+m} + theta_n)**2,

    the maximally overlapped form, which reuses every stride-m second difference
    and so has the smallest variance in the standard family. The result carries
    the units of the underlying RATE, not of the phase.
    """
    x = np.asarray(phase, dtype=float)
    if x.ndim != 1:
        raise ValueError(f"phase record must be 1-D, got shape {x.shape}")
    if m < 1:
        raise ValueError(f"cluster count m must be at least 1, got {m}")
    n_theta = x.size
    if n_theta - 2 * m < 1:
        raise ValueError(
            f"record of {n_theta} points is too short for m={m} "
            f"(needs at least {2 * m + 1})"
        )
    if dt_s <= 0.0:
        raise ValueError(f"sample interval must be positive, got {dt_s}")
    tau = m * dt_s
    # Vectorized second difference: the three shifted views cost no copy beyond
    # the difference itself, which matters at N = 1e6 and m sweeping octaves.
    second_diff = x[2 * m :] - 2.0 * x[m : n_theta - m] + x[: n_theta - 2 * m]
    return float(np.sum(second_diff**2) / (2.0 * tau**2 * (n_theta - 2 * m)))


def overlapping_allan_deviation(phase: np.ndarray, dt_s: float, m: int) -> float:
    """Square root of :func:`overlapping_allan_variance` (ADEV)."""
    return float(np.sqrt(overlapping_allan_variance(phase, dt_s, m)))


def adev_curve(
    phase: np.ndarray, dt_s: float, m_values: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """ADEV over a set of cluster counts; returns ``(tau, adev)``."""
    ms = np.asarray(m_values, dtype=int)
    taus = ms * dt_s
    adevs = np.array([overlapping_allan_deviation(phase, dt_s, int(m)) for m in ms])
    return taus, adevs


def octave_m_grid(n_theta: int, dt_s: float, tau_max_s: float) -> np.ndarray:
    """Octave cluster grid ``m = 2**j`` restricted to ``tau <= tau_max``.

    Section ``sec:imu:recovery`` step 1 specifies an octave grid capped at
    ``T/10``; the cap is what keeps every estimate backed by enough independent
    second differences to be meaningful.
    """
    m_max = int(tau_max_s / dt_s)
    ms = []
    m = 1
    while m <= m_max and n_theta - 2 * m >= 1:
        ms.append(m)
        m *= 2
    if not ms:
        raise ValueError(
            f"no admissible cluster times for N={n_theta}, dt={dt_s}, tau_max={tau_max_s}"
        )
    return np.array(ms, dtype=int)


def white_noise_adev(tau_s: np.ndarray, n_coeff: float) -> np.ndarray:
    """White-rate-noise ADEV, ``eq:imu:whiteslope``: ``sigma(tau) = N/sqrt(tau)``.

    ``N`` is the random-walk coefficient in rad/sqrt(s) (gyro) or
    (m/s)/sqrt(s) (accelerometer). The -1/2 log-log slope and the read-at-one-
    second identification ``N = sigma(1 s)`` follow directly.
    """
    return n_coeff / np.sqrt(np.asarray(tau_s, dtype=float))


def gauss_markov_allan_variance(
    tau_s: np.ndarray, sigma_gm: float, tau_c_s: float
) -> np.ndarray:
    """First-order Gauss-Markov Allan variance, ``eq:imu:gmadev``.

        var(tau) = (2 sigma**2 tau_c / tau)
                   [1 - (tau_c / (2 tau)) (3 - 4 exp(-x) + exp(-2x))],
        x = tau / tau_c.

    Derived in the chapter from the process autocorrelation
    ``R(s) = sigma**2 exp(-|s|/tau_c)``; ``allan_variance_from_autocorrelation``
    in the test suite reproduces it by direct numerical integration of that
    kernel, which is the independent check that the closed form is right.
    """
    if tau_c_s <= 0.0:
        raise ValueError(f"correlation time must be positive, got {tau_c_s}")
    tau = np.asarray(tau_s, dtype=float)
    x = tau / tau_c_s
    bracket = 1.0 - (tau_c_s / (2.0 * tau)) * (
        3.0 - 4.0 * np.exp(-x) + np.exp(-2.0 * x)
    )
    return (2.0 * sigma_gm**2 * tau_c_s / tau) * bracket


def gauss_markov_adev(
    tau_s: np.ndarray, sigma_gm: float, tau_c_s: float
) -> np.ndarray:
    """Square root of :func:`gauss_markov_allan_variance`."""
    return np.sqrt(gauss_markov_allan_variance(tau_s, sigma_gm, tau_c_s))


def gauss_markov_peak() -> tuple[float, float]:
    """Locate the interior ADEV maximum of ``eq:imu:gmadev``, ``eq:imu:gmpeak``.

    Returns ``(tau_star / tau_c, sigma(tau_star) / sigma_gm)``, both
    dimensionless because the curve scales exactly in those variables. Found by
    golden-section search on a coarse bracket rather than transcribed from the
    chapter's 1.8926 / 0.6174, so the chapter's constants are verified.
    """
    # The peak sits near tau_c by inspection of the +1/2 and -1/2 asymptotes, so
    # a decade either side is a safe bracket.
    lo, hi = 0.1, 20.0
    invphi = (np.sqrt(5.0) - 1.0) / 2.0
    a, b = lo, hi
    c = b - invphi * (b - a)
    d = a + invphi * (b - a)
    fc = float(gauss_markov_adev(np.array([c]), 1.0, 1.0)[0])
    fd = float(gauss_markov_adev(np.array([d]), 1.0, 1.0)[0])
    for _ in range(200):
        if fc > fd:
            b, d, fd = d, c, fc
            c = b - invphi * (b - a)
            fc = float(gauss_markov_adev(np.array([c]), 1.0, 1.0)[0])
        else:
            a, c, fc = c, d, fd
            d = a + invphi * (b - a)
            fd = float(gauss_markov_adev(np.array([d]), 1.0, 1.0)[0])
        if b - a < 1e-14:
            break
    x_star = 0.5 * (a + b)
    return x_star, float(gauss_markov_adev(np.array([x_star]), 1.0, 1.0)[0])


TAU_STAR_OVER_TAU_C, ADEV_PEAK_OVER_SIGMA_GM = gauss_markov_peak()


def sigma_gm_from_bias_instability(bias_instability: float) -> float:
    """Preset mapping ``eq:imu:presetmap``.

    ``sigma_GM = (sqrt(2 ln2 / pi) / 0.617364) B``, chosen so the Gauss-Markov
    ADEV peak equals ``0.664 B`` exactly and the conventional read-the-flat-
    region identification of ``eq:imu:bi`` returns the configured coefficient.
    The denominator is recomputed here from :func:`gauss_markov_peak` rather
    than transcribed.
    """
    return BIAS_INSTABILITY_FACTOR / ADEV_PEAK_OVER_SIGMA_GM * bias_instability


def bias_instability_from_sigma_gm(sigma_gm: float) -> float:
    """Inverse of :func:`sigma_gm_from_bias_instability`."""
    return ADEV_PEAK_OVER_SIGMA_GM / BIAS_INSTABILITY_FACTOR * sigma_gm


def quantization_adev(tau_s: np.ndarray, quantum: float) -> np.ndarray:
    """Quantization ADEV, ``eq:imu:quantadev``: ``sigma(tau) = q / (2 tau)``.

    White phase noise of variance ``q**2/12`` has Allan variance
    ``3 (q**2/12) / tau**2``; the square root is ``q/(2 tau)``, a -1 log-log
    slope that dominates only at the shortest cluster times.
    """
    return quantum / (2.0 * np.asarray(tau_s, dtype=float))


def model_adev(
    tau_s: np.ndarray,
    n_coeff: float,
    sigma_gm: float,
    tau_c_s: float,
    quantum: float,
) -> np.ndarray:
    """Total model ADEV: the three independent contributions in quadrature.

    ``sqrt(N**2/tau + var_GM(tau) + var_Q(tau))``, the overlay curve named in
    the chapter's Allan-recovery validation item. The terms add in variance
    because the three noise processes are independent by construction.
    """
    tau = np.asarray(tau_s, dtype=float)
    return np.sqrt(
        n_coeff**2 / tau
        + gauss_markov_allan_variance(tau, sigma_gm, tau_c_s)
        + quantization_adev(tau, quantum) ** 2
    )


@dataclass(frozen=True)
class ImuAxisConfig:
    """Single-axis static-record noise configuration, in SI units.

    ``n_coeff`` is the random-walk coefficient (rad/sqrt(s) or (m/s)/sqrt(s));
    ``bias_instability`` is the data-sheet ``B`` (rad/s or m/s**2); ``tau_c_s``
    is the Gauss-Markov correlation time; ``quantum`` is the output quantum
    (rad or m/s), zero to disable quantization.
    """

    n_coeff: float
    bias_instability: float
    tau_c_s: float
    quantum: float = 0.0

    def __post_init__(self) -> None:
        if self.n_coeff < 0.0 or self.bias_instability < 0.0 or self.quantum < 0.0:
            raise ValueError("noise coefficients and the quantum must be non-negative")
        if self.tau_c_s <= 0.0:
            raise ValueError(f"correlation time must be positive, got {self.tau_c_s}")

    @property
    def sigma_gm(self) -> float:
        """Gauss-Markov process strength implied by ``B``, ``eq:imu:presetmap``."""
        return sigma_gm_from_bias_instability(self.bias_instability)


def synthesize_static_record(
    config: ImuAxisConfig,
    dt_s: float,
    duration_s: float,
    rng: np.random.Generator,
) -> np.ndarray:
    """Generate one axis of a static-truth increment record.

    Truth is static (``omega = 0``, ``f = 0``, section ``sec:imu:recovery``), so
    the emitted increment is the error chain alone. Implements, per sample and
    in the chapter's normative evaluation order:

    1. advance the Gauss-Markov bias, ``eq:imu:gm``:
       ``b_k = phi b_{k-1} + w_k``, ``phi = exp(-dt/tau_c)``,
       ``w_k ~ N(0, sigma**2 (1 - phi**2))``, initialized from the stationary
       distribution ``b_0 ~ N(0, sigma**2)``;
    2. form ``u_k = b_k dt + eta_k`` with ``eta_k ~ N(0, (N sqrt(dt))**2)``,
       ``eq:imu:arw``;
    3. quantize with residual carry, ``eq:imu:quant``:
       ``s_k = u_k + rho_{k-1}``, ``y_k = q floor(s_k/q + 1/2)``,
       ``rho_k = s_k - y_k``, ``rho_0 = 0``.

    Turn-on bias and the scale-factor/misalignment matrix are deliberately
    omitted: on a static record a constant bias contributes a deterministic ramp
    that the Allan second difference annihilates exactly, and ``M`` multiplies a
    zero truth increment. Their omission therefore cannot change the recovered
    coefficients, which is asserted in the test suite rather than assumed here.

    Returns the emitted increment array of length ``round(duration/dt)``.
    """
    if dt_s <= 0.0:
        raise ValueError(f"sample interval must be positive, got {dt_s}")
    n = int(round(duration_s / dt_s))
    if n < 2:
        raise ValueError(f"record must hold at least two samples, got {n}")

    phi = np.exp(-dt_s / config.tau_c_s)
    sigma_gm = config.sigma_gm
    drive_sigma = sigma_gm * np.sqrt(1.0 - phi**2)
    arw_sigma = config.n_coeff * np.sqrt(dt_s)

    # Draw both streams up front: the recursion below is inherently sequential,
    # but its inputs are not, and the vectorized draw dominates the runtime at
    # N = 1e6.
    drives = rng.normal(0.0, drive_sigma, size=n) if drive_sigma > 0.0 else np.zeros(n)
    whites = rng.normal(0.0, arw_sigma, size=n) if arw_sigma > 0.0 else np.zeros(n)
    bias = rng.normal(0.0, sigma_gm) if sigma_gm > 0.0 else 0.0

    biases = np.empty(n)
    for k in range(n):
        bias = phi * bias + drives[k]
        biases[k] = bias

    pre_quant = biases * dt_s + whites
    if config.quantum <= 0.0:
        return pre_quant
    return quantize_with_carry(pre_quant, config.quantum)


def quantize_with_carry(values: np.ndarray, quantum: float) -> np.ndarray:
    """Carry-preserving quantizer, ``eq:imu:quant``.

    Round-half-up via the floor function, with the sub-quantum residual carried
    into the next sample so accumulation is lossless: the accumulated output
    never departs from the accumulated input by more than half a quantum, which
    is how a rate-integrating output register actually behaves.
    """
    if quantum <= 0.0:
        raise ValueError(f"quantum must be positive, got {quantum}")
    u = np.asarray(values, dtype=float)
    out = np.empty_like(u)
    residual = 0.0
    for k in range(u.size):
        s = u[k] + residual
        y = quantum * np.floor(s / quantum + 0.5)
        out[k] = y
        residual = s - y
    return out


def phase_from_increments(increments: np.ndarray) -> np.ndarray:
    """Accumulated-angle (phase) record with ``theta_0 = 0`` prepended.

    Section ``sec:imu:allanderivation`` defines the Allan estimator on the
    phase record, so the increment stream the sensor emits must be cumulatively
    summed before :func:`overlapping_allan_variance` sees it.
    """
    inc = np.asarray(increments, dtype=float)
    phase = np.empty(inc.size + 1)
    phase[0] = 0.0
    np.cumsum(inc, out=phase[1:])
    return phase


def gm_to_white_ratio_at_peak(config: "ImuAxisConfig") -> float:
    """Ratio of the Gauss-Markov to the white Allan variance at ``tau*``.

    This ratio governs whether the exit-criterion-1 gate on ``B`` is
    statistically achievable, and it is not discussed in the chapter. Equation
    ``eq:imu:recoverybi`` recovers ``B`` by subtracting the white term
    ``N**2/tau*`` from the measured Allan variance at the peak. Writing
    ``A = adev(tau*)**2``, ``W = N**2/tau*`` and ``G = A - W`` for the surviving
    Gauss-Markov part, the estimator error propagates as

        dB/B = (1/2) dG/G = (1/2) (A/G) (dA/A) = (A/G) (d adev / adev),

    so a small ``G/W`` AMPLIFIES the Allan estimator's own scatter by
    ``A/G = 1 + W/G``. With the estimator scatter at ``tau*`` running about 4 %
    on a 1e4 s record, a configuration with ``G/W = 0.46`` inflates it to about
    12 % and fails the +/- 10 % gate roughly 40 % of the time -- measured, not
    predicted, in ``tests/python/test_refs_allan.py``.

    A ratio of about 4 or more keeps the amplification under 1.25 and the gate
    comfortably reliable; :func:`min_bias_instability_for_ratio` inverts the
    relation into a preset design rule.
    """
    tau_star = TAU_STAR_OVER_TAU_C * config.tau_c_s
    white_var = config.n_coeff**2 / tau_star
    if white_var == 0.0:
        return float("inf")
    gm_var = (BIAS_INSTABILITY_FACTOR * config.bias_instability) ** 2
    return float(gm_var / white_var)


def min_bias_instability_for_ratio(
    n_coeff: float, tau_c_s: float, ratio: float = 4.0
) -> float:
    """Smallest ``B`` meeting a target :func:`gm_to_white_ratio_at_peak`.

    Inverting the ratio definition:
    ``B >= sqrt(ratio) N / (0.664282 sqrt(1.8926 tau_c))``. Use it to choose a
    gate-scenario preset whose bias instability is actually identifiable from a
    1e4 s record, rather than discovering the marginality from a flaky gate.
    """
    if tau_c_s <= 0.0 or ratio <= 0.0:
        raise ValueError(f"tau_c and ratio must be positive, got {tau_c_s}, {ratio}")
    tau_star = TAU_STAR_OVER_TAU_C * tau_c_s
    return float(np.sqrt(ratio) * n_coeff / (BIAS_INSTABILITY_FACTOR * np.sqrt(tau_star)))


@dataclass(frozen=True)
class Recovery:
    """Result of the section ``sec:imu:recovery`` identification."""

    n_hat: float
    b_hat: float
    n_error: float
    b_error: float
    adev_one_second: float
    adev_at_peak: float
    tau_star_s: float
    passed: bool


def recover_coefficients(
    increments: np.ndarray,
    dt_s: float,
    config: ImuAxisConfig,
    tolerance: float = 0.10,
) -> Recovery:
    """Run the exit-criterion-1 recovery of section ``sec:imu:recovery``.

    Steps 2 and 3 of the chapter procedure. The configured correlation time and
    quantum are inputs to the recovery -- it re-identifies the noise MAGNITUDES
    ``N`` and ``B``, not the whole parameter set:

        N_hat = sqrt(adev(1 s)**2 - var_GM(1 s) - var_Q(1 s))       eq:imu:recovery
        B_hat = sqrt(adev(tau*)**2 - N_hat**2/tau* - var_Q(tau*)) / 0.664282
                                                              eq:imu:recoverybi

    with ``tau* = 1.8926 tau_c`` the analytically known Gauss-Markov peak. The
    gate is ``|N_hat/N - 1| <= 0.10`` and ``|B_hat/B - 1| <= 0.10``.

    A negative radicand -- possible when the true coefficient is small relative
    to the terms being subtracted -- is reported as NaN rather than clamped,
    so the failure is visible instead of silently producing a plausible number.
    """
    phase = phase_from_increments(increments)

    m_one = int(round(1.0 / dt_s))
    if not np.isclose(m_one * dt_s, 1.0, rtol=0.0, atol=1e-12):
        raise ValueError(
            f"sample interval {dt_s} s does not divide 1 s into an integer "
            "cluster count; section sec:imu:recovery requires it"
        )
    adev_1s = overlapping_allan_deviation(phase, dt_s, m_one)

    tau_star = TAU_STAR_OVER_TAU_C * config.tau_c_s
    m_star = max(1, int(round(tau_star / dt_s)))
    # Snap tau* onto the sample grid: the estimator only exists at integer
    # cluster counts, and the model terms below must be evaluated at the same
    # tau the estimator actually used or the subtraction is inconsistent.
    tau_star_grid = m_star * dt_s
    adev_star = overlapping_allan_deviation(phase, dt_s, m_star)

    sigma_gm = config.sigma_gm
    var_gm_1s = float(gauss_markov_allan_variance(np.array([1.0]), sigma_gm, config.tau_c_s)[0])
    var_q_1s = float(quantization_adev(np.array([1.0]), config.quantum)[0] ** 2) if config.quantum > 0.0 else 0.0
    radicand_n = adev_1s**2 - var_gm_1s - var_q_1s
    n_hat = float(np.sqrt(radicand_n)) if radicand_n > 0.0 else float("nan")

    var_q_star = (
        float(quantization_adev(np.array([tau_star_grid]), config.quantum)[0] ** 2)
        if config.quantum > 0.0
        else 0.0
    )
    radicand_b = adev_star**2 - n_hat**2 / tau_star_grid - var_q_star
    b_hat = (
        float(np.sqrt(radicand_b)) / BIAS_INSTABILITY_FACTOR
        if radicand_b > 0.0
        else float("nan")
    )

    n_error = n_hat / config.n_coeff - 1.0 if config.n_coeff > 0.0 else float("nan")
    b_error = (
        b_hat / config.bias_instability - 1.0
        if config.bias_instability > 0.0
        else float("nan")
    )
    passed = bool(abs(n_error) <= tolerance and abs(b_error) <= tolerance)

    return Recovery(
        n_hat=n_hat,
        b_hat=b_hat,
        n_error=n_error,
        b_error=b_error,
        adev_one_second=adev_1s,
        adev_at_peak=adev_star,
        tau_star_s=tau_star_grid,
        passed=passed,
    )
