#!/usr/bin/env python3
"""Two-key golden regeneration tool (FR-22 layer 6): the only way to change the
Monte Carlo regression golden, key 1 (human intent).

This is the sanctioned half of the two-key golden-update policy. It re-runs the
frozen Monte Carlo regression sweep (``missions/mc_regression_sweep.toml``), computes
the ensemble's outcome-metric statistics, and compares them to the committed
golden (``tests/golden/mc_regression/energy_stats.toml``):

* by default it is a DRY RUN -- it prints a unified diff summary of the old
  versus new statistics and exits nonzero if any change is pending, changing
  nothing on disk. This is the "tooling that emits a diff summary" the PRD
  requires, and it is safe to run in review or CI to see whether a golden is
  stale.
* with ``--apply`` (the human-intent key) it writes the new value file AND
  rewrites the directory's ``manifest.toml`` with a fresh ``date``,
  ``generation`` note, and -- the mechanical link the CI gate
  (``scripts/check_golden_manifests.py``, key 2) enforces -- the value file's
  new ``values_sha256``.

Because the value file and its recorded hash are only ever written together
here, a hand-edit of the value file changes its bytes but not the manifest hash
and CI rejects it; a regeneration through ``--apply`` updates both and CI
passes. The sweep is bit-reproducible from its master seed, so on an unchanged
binary a dry run reports "no change" and ``--apply`` is a no-op diff.

Exit status: 0 when the golden is up to date (dry run) or was written
(``--apply``); 1 when a dry run finds a pending change; 2 on a runtime failure
(the compiled core is required to run the sweep).
"""

from __future__ import annotations

import argparse
import datetime
import difflib
import hashlib
import sys
import tempfile
import tomllib
from pathlib import Path


def repo_root_default() -> Path:
    # The script lives in <root>/scripts/, so the default root is its parent.
    return Path(__file__).resolve().parent.parent


# The manifest's generation prose, kept beside the tool that produces the
# values so the recorded procedure and the actual procedure cannot drift.
_GENERATION = (
    "energy_stats.toml is regenerated by scripts/golden_update.py --apply, "
    "which runs the 128-run Latin-hypercube sweep missions/mc_regression_sweep.toml "
    "over the committed EGM2008 8x8 LEO mission (no fetched ephemeris), reads "
    "each run's final osculating specific mechanical energy energy_m2ps2 from "
    "the truth trajectory via the SRLOG loader, and freezes the ensemble size "
    "n, the metric mean, and the sample (ddof=1) standard deviation. The sweep "
    "is bit-reproducible from its master seed, so the statistics are exact "
    "numbers, recorded as binary64 hex literals. The Phase 7 exit-criterion-2 "
    "gate (star_reacher.mc_regression) checks a re-run's ensemble against these "
    "with a chi-square 99% two-sided interval on the standardized sum of "
    "squares and an Anderson-Darling 99% test of the standardized metric "
    "against N(mean, std)."
)

_CITATION = (
    "Anderson & Darling, 'A Test of Goodness of Fit', J. Amer. Statist. Assoc. "
    "49(268), 1954, with the finite-n distribution of Marsaglia & Marsaglia, "
    "'Evaluating the Anderson-Darling Distribution', J. Stat. Soft. 9(2), 2004 "
    "(star_reacher.anderson); the chi-square two-sided interval per "
    "star_reacher.consistency / Bar-Shalom, Li & Kirubarajan, 'Estimation with "
    "Applications to Tracking and Navigation', Wiley 2001, ch. 5. The frozen "
    "values are the outputs of the committed deterministic sweep, not a "
    "published constant."
)

_TOLERANCE = (
    "gate, not a per-value tolerance: the chi-square statistic S = sum "
    "((x-mean)/std)^2 must lie in [chi2_ppf(0.005, n), chi2_ppf(0.995, n)] and "
    "the Anderson-Darling p-value of the standardized metric against N(mean, "
    "std) must be >= 0.01. Measured at the frozen ensemble: S = 127.000 in "
    "[90.543, 172.957]; A2 = 1.408, p = 0.200. values_sha256 is exact byte "
    "equality of the value file."
)


def _run_sweep_stats(repo_root: Path, workers: int):
    """Run the regression sweep and return the fresh :class:`GoldenStats`.

    Runs from the repo root so the base mission's relative gravity-field path
    resolves, into a throwaway output directory.
    """
    import os

    from star_reacher.mc import run_sweep
    from star_reacher.mc_regression import ensemble_metric, summarize_metric

    spec = repo_root / "missions" / "mc_regression_sweep.toml"
    cwd = os.getcwd()
    os.chdir(repo_root)
    try:
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "out"
            manifest = run_sweep(str(spec), workers=workers, outdir=str(out),
                                 force=True)
            failed = [r for r in manifest["runs"] if r["status"] != "success"]
            if failed:
                raise RuntimeError(
                    f"{len(failed)} of {len(manifest['runs'])} sweep runs "
                    f"failed (first: {failed[0].get('error')})"
                )
            metric = ensemble_metric(manifest, out)
            return summarize_metric(metric, mission=manifest["sweep"]["mission"])
    finally:
        os.chdir(cwd)


def _stat_lines(label: str, doc: dict) -> list[str]:
    # A stable, human-readable rendering of the compared statistics for the
    # diff summary. The hex fields make the diff exact; the readable decimals
    # make it legible.
    return [
        f"{label} metric = {doc.get('metric')}",
        f"{label} mission = {doc.get('mission')}",
        f"{label} n = {doc.get('n')}",
        f"{label} mean_hex = {doc.get('mean_hex')}",
        f"{label} std_hex = {doc.get('std_hex')}",
        f"{label} mean = {doc.get('mean_readable')}",
        f"{label} std = {doc.get('std_readable')}",
    ]


def _write_manifest(manifest_path: Path, value_name: str, value_sha: str,
                    date: str) -> None:
    """Rewrite the golden manifest with the fresh value hash and date."""
    text = (
        "# Provenance manifest for the Monte Carlo regression golden in this\n"
        "# directory (FR-22 layer 6: uncited golden = lint failure; schema in\n"
        "# tests/golden/README.md). The values_sha256 field is the two-key\n"
        "# hash-gate: scripts/check_golden_manifests.py rejects any edit to a\n"
        "# value file that did not go through scripts/golden_update.py --apply.\n"
        "\n"
        "schema_version = 1\n"
        "\n"
        "[golden]\n"
        'directory = "mc_regression"\n'
        f'date = "{date}"\n'
        'generation = """\n'
        f"{_GENERATION}\n"
        '"""\n'
        "\n"
        "[[file]]\n"
        f'name = "{value_name}"\n'
        'source = "scripts/golden_update.py --apply, from the deterministic sweep missions/mc_regression_sweep.toml"\n'
        f'citation = "{_CITATION}"\n'
        'generation = "scripts/golden_update.py --apply (runs the sweep, freezes n/mean/std)"\n'
        f'date = "{date}"\n'
        f'tolerance = "{_TOLERANCE}"\n'
        f'values_sha256 = "{value_sha}"\n'
    )
    # LF bytes, matching the value file, for clean diffs under the repo's
    # `* text=auto` normalization.
    manifest_path.write_bytes(text.encode("utf-8"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    root = repo_root_default()
    parser.add_argument(
        "--repo-root", type=Path, default=root,
        help="repository root (default: the script's parent's parent)",
    )
    parser.add_argument(
        "--apply", action="store_true",
        help="write the new value file and manifest (key 1: human intent); "
             "without it this is a dry run that only prints the diff",
    )
    parser.add_argument(
        "--workers", type=int, default=1,
        help="sweep worker processes (default 1: in-process, avoids the "
             "process-pool flakiness on some hosts; the result is "
             "worker-count-independent by D-10)",
    )
    args = parser.parse_args(argv)

    repo_root = args.repo_root
    golden_dir = repo_root / "tests" / "golden" / "mc_regression"
    from star_reacher.mc_regression import (
        GOLDEN_VALUE_FILE,
        format_golden_toml,
        golden_stats_dict,
    )

    value_path = golden_dir / GOLDEN_VALUE_FILE
    manifest_path = golden_dir / "manifest.toml"

    try:
        stats = _run_sweep_stats(repo_root, args.workers)
    except Exception as exc:  # noqa: BLE001 - a runtime failure is exit 2
        print(f"golden_update: could not regenerate the sweep statistics: "
              f"{type(exc).__name__}: {exc}", file=sys.stderr)
        return 2

    # Encode once, hash the exact bytes that go to disk. The value file is
    # committed under `* text=auto` LF normalization (.gitattributes), so it
    # must carry LF regardless of host, and the recorded hash must be of those
    # exact bytes -- the check gate re-hashes the file's raw bytes.
    new_text = format_golden_toml(stats)
    new_bytes = new_text.encode("utf-8")
    new_sha = hashlib.sha256(new_bytes).hexdigest()

    old_bytes = value_path.read_bytes() if value_path.is_file() else b""
    old_text = old_bytes.decode("utf-8")
    old_doc = tomllib.loads(old_text) if old_text else {}

    # A stat-level diff summary (not the raw file diff), so the human sees the
    # numbers that changed rather than comment or formatting noise.
    old_lines = _stat_lines("old", old_doc) if old_doc else ["old (no committed golden)"]
    new_lines = _stat_lines("new", golden_stats_dict(stats) | {
        "mean_readable": stats.mean, "std_readable": stats.std})
    diff = list(difflib.unified_diff(
        [ln.replace("old ", "", 1) for ln in old_lines],
        [ln.replace("new ", "", 1) for ln in new_lines],
        fromfile="golden (committed)", tofile="regenerated", lineterm="",
    ))

    changed = new_bytes != old_bytes
    print("golden_update: Monte Carlo regression golden "
          f"({value_path.relative_to(repo_root)})")
    if not changed:
        print("golden_update: no change -- the committed golden matches a fresh "
              "regeneration of the sweep.")
        return 0

    print("golden_update: DIFF SUMMARY (committed golden vs regenerated):")
    if diff:
        for line in diff:
            print(f"  {line}")
    else:
        # Values equal but bytes differ (e.g. comment/header change).
        print("  (statistics unchanged; value-file bytes differ)")
    print(f"  values_sha256 (new): {new_sha}")

    if not args.apply:
        print("golden_update: dry run -- a change is pending. Re-run with "
              "--apply to write the value file and manifest together.",
              file=sys.stderr)
        return 1

    date = datetime.date.today().isoformat()
    # Write raw LF bytes (newline="" would still let write_text translate); the
    # recorded values_sha256 is the hash of exactly these bytes.
    value_path.write_bytes(new_bytes)
    _write_manifest(manifest_path, GOLDEN_VALUE_FILE, new_sha, date)
    print(f"golden_update: APPLIED -- wrote {value_path.relative_to(repo_root)} "
          f"and updated {manifest_path.relative_to(repo_root)} "
          f"(values_sha256 {new_sha}, date {date}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
